In [76]:
import numpy as np
import pandas as pd

# **Data Selection**

In [77]:
data = pd.read_csv("C:/Users/Atharva Nair/kavaach/ml-model/data/combined_final_dataset.csv")
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81380 entries, 0 to 81379
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Text          81380 non-null  object
 1   Fear          81380 non-null  int64
 2   Anxiety       81380 non-null  int64
 3   Panic         81380 non-null  int64
 4   Distress      81380 non-null  int64
 5   Urgency       81380 non-null  int64
 6   Coercion      81380 non-null  int64
 7   Aggression    81380 non-null  int64
 8   Helplessness  81380 non-null  int64
 9   Calm          81380 non-null  int64
dtypes: int64(9), object(1)
memory usage: 6.2+ MB

# **Data Preparation**

In [78]:
data.isnull().sum()

Text            0
Fear            0
Anxiety         0
Panic           0
Distress        0
Urgency         0
Coercion        0
Aggression      0
Helplessness    0
Calm            0
dtype: int64

In [79]:
data.sample(20)

,Text,Fear,Anxiety,Panic,Distress,Urgency,Coercion,Aggression,Helplessness,Calm
51996,ATM has scored only 27 goals in 19 games and h...,0,0,0,0,0,0,1,0,0
62345,ah dang sorry. in that case idk.,0,0,0,1,0,0,0,1,0
25668,One time while I was waking up in the middle o...,1,0,1,0,0,0,0,0,0
11180,I'm a 35 year old man who has never had a girl...,0,0,0,0,0,0,0,0,1
57156,Lol alright dude. Nice chat.,0,0,0,0,0,0,0,0,1
72076,"This is the most perfect , and fitting meme in...",0,0,0,0,0,0,0,0,1
21342,I just won $300 dollars on a scratch off ticke...,0,0,0,0,0,0,0,0,1
40053,"I come up and hug her and say good morning, us...",0,0,0,0,0,0,0,0,1
5908,I ate ten Big Macs last night because I was so...,0,0,0,1,0,0,0,1,0
28589,Go you!,0,0,0,0,0,0,0,0,1
52684,"[NAME] pnr play has not been good, they are de...",0,0,0,0,0,1,0,0,0
55783,I was responding to the title of the post (not...,0,1,0,0,0,0,0,0,0
3457,I had a big argument with my mom over who lost...,0,0,0,1,0,0,0,1,0
22390,sentimental: playing old school games with my bro,0,0,0,1,0,0,0,0,1
27209,"Apologies, I take it all back as I’ve just see...",0,0,0,1,0,0,0,1,0
74932,Yeah I legitimately have no idea what he's tal...,0,0,0,0,0,0,0,0,1
46763,I understand just so hard feels like I’m being...,0,0,0,0,0,0,0,0,1
9128,"I thought i saw a ghost outside my window, I h...",1,0,1,0,0,0,0,0,0
19679,I interviewed for a job. I thought it went great.,0,0,0,0,0,0,0,0,1
13229,My mom used to put one of my christmas present...,0,1,0,0,1,0,0,0,0

In [80]:
data["Fear"].value_counts()

Fear
0    78521
1     2859
Name: count, dtype: int64

In [81]:
# !pip install sklearn

In [82]:
# !pip install scikit-learn

In [83]:
from sklearn.model_selection import train_test_split

df_train, df_test1 = train_test_split(data, test_size = 0.2, random_state = 42)
df_val, df_test = train_test_split(df_test1, test_size=0.5, random_state = 42)

In [84]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 65104 entries, 8600 to 15795
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Text          65104 non-null  object
 1   Fear          65104 non-null  int64
 2   Anxiety       65104 non-null  int64
 3   Panic         65104 non-null  int64
 4   Distress      65104 non-null  int64
 5   Urgency       65104 non-null  int64
 6   Coercion      65104 non-null  int64
 7   Aggression    65104 non-null  int64
 8   Helplessness  65104 non-null  int64
 9   Calm          65104 non-null  int64
dtypes: int64(9), object(1)
memory usage: 5.5+ MB

In [85]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8138 entries, 51987 to 19172
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Text          8138 non-null   object
 1   Fear          8138 non-null   int64
 2   Anxiety       8138 non-null   int64
 3   Panic         8138 non-null   int64
 4   Distress      8138 non-null   int64
 5   Urgency       8138 non-null   int64
 6   Coercion      8138 non-null   int64
 7   Aggression    8138 non-null   int64
 8   Helplessness  8138 non-null   int64
 9   Calm          8138 non-null   int64
dtypes: int64(9), object(1)
memory usage: 699.4+ KB

In [86]:
df_val.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8138 entries, 13888 to 41611
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Text          8138 non-null   object
 1   Fear          8138 non-null   int64
 2   Anxiety       8138 non-null   int64
 3   Panic         8138 non-null   int64
 4   Distress      8138 non-null   int64
 5   Urgency       8138 non-null   int64
 6   Coercion      8138 non-null   int64
 7   Aggression    8138 non-null   int64
 8   Helplessness  8138 non-null   int64
 9   Calm          8138 non-null   int64
dtypes: int64(9), object(1)
memory usage: 699.4+ KB

# **Model Modeling**

### **Tokenizing English sentences**

In [87]:
from transformers import DistilBertTokenizer

tokenizer = DistilBertTokenizer.from_pretrained("distilbert-base-uncased")

In [88]:
def convert_tokenizer(example):
    return tokenizer(
        example["Text"],
        truncation = True,
        padding = "max_length",
        max_length = 128
    )

In [89]:
# !pip install datasets

In [90]:
from datasets import Dataset

train_dataset = Dataset.from_pandas(df_train)
test_dataset = Dataset.from_pandas(df_test)
val_dataset = Dataset.from_pandas(df_val)

In [91]:
train_dataset = train_dataset.map(
    convert_tokenizer,
    batched = True,
)

test_dataset = test_dataset.map(
    convert_tokenizer,
    batched = True,
)

val_dataset = val_dataset.map(
    convert_tokenizer,
    batched = True,
)

Map: 100%|██████████| 65104/65104 [00:02<00:00, 26051.62 examples/s]
Map: 100%|██████████| 8138/8138 [00:00<00:00, 27302.29 examples/s]
Map: 100%|██████████| 8138/8138 [00:00<00:00, 27576.65 examples/s]

In [92]:
print(train_dataset[0])

{'Text': 'Sitting at a computer at 3am with the lights off alone.', 'Fear': 0, 'Anxiety': 0, 'Panic': 0, 'Distress': 1, 'Urgency': 0, 'Coercion': 0, 'Aggression': 0, 'Helplessness': 1, 'Calm': 0, '__index_level_0__': 8600, 'input_ids': [101, 3564, 2012, 1037, 3274, 2012, 23842, 2213, 2007, 1996, 4597, 2125, 2894, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}

### **Converting basic english labels into a group of 1 and 0 to get a array**

In [93]:
emotion_labels = [
    "Fear",
    "Anxiety",
    "Panic",
    "Distress",
    "Urgency",
    "Coercion",
    "Aggression",
    "Helplessness",
    "Calm",
]

def create_labels(examples):
    examples["labels"] = [
        1.0* examples[label]
        for label in emotion_labels
    ]
    return examples

In [97]:
train_dataset = train_dataset.map(create_labels)
test_dataset = test_dataset.map(create_labels)
val_dataset = val_dataset.map(create_labels)

Map: 100%|██████████| 65104/65104 [00:08<00:00, 8130.50 examples/s]
Map: 100%|██████████| 8138/8138 [00:00<00:00, 9152.57 examples/s]
Map: 100%|██████████| 8138/8138 [00:01<00:00, 7701.85 examples/s]

In [164]:
# labels_matrix = np.array(train_dataset["labels"])

# calm_idx = emotion_labels.index("Calm")

# print(
#     labels_matrix[:, calm_idx].mean()
# )

for emotion in emotion_labels:
    if emotion != "Calm":

        overlap = sum(
            calm == 1 and emo == 1
            for calm, emo in zip(
                train_dataset["Calm"],
                train_dataset[emotion]
            )
        )

        print(emotion, overlap)

Fear 0
Anxiety 0
Panic 0
Distress 1147
Urgency 1206
Coercion 0
Aggression 0
Helplessness 0

### **Calculating Weights of each label**

In [98]:
import numpy as np
labels_matrix = np.array(train_dataset["labels"])
labels_matrix.shape

(65104, 9)

In [99]:
label_counts = labels_matrix.sum(axis=0)
label_counts

array([ 2303.,  7276.,  2965.,  9379.,  7335.,  4695.,  5963.,  6428.,
       40751.])

In [100]:
for emotion, count in zip(emotion_labels, label_counts):
    print(emotion, "\t" , count)

Fear 	 2303.0
Anxiety 	 7276.0
Panic 	 2965.0
Distress 	 9379.0
Urgency 	 7335.0
Coercion 	 4695.0
Aggression 	 5963.0
Helplessness 	 6428.0
Calm 	 40751.0

In [ ]:
weights = len(data) / (len(emotion_labels)* label_counts)
weights

array([3.92627973, 1.24274632, 3.04965336, 0.96409236, 1.23275013,
       1.92592593, 1.5163881 , 1.40669294, 0.22188958])

In [102]:
for emotion, w in zip(emotion_labels, weights):
    print(emotion, "\t" ,w)

Fear 	 3.9262797317508564
Anxiety 	 1.2427463197116853
Panic 	 3.0496533633127223
Distress 	 0.9640923576311144
Urgency 	 1.2327501325456336
Coercion 	 1.9259259259259258
Aggression 	 1.5163880969683419
Helplessness 	 1.4066929406070663
Calm 	 0.2218895787151781

### **Implementing Binary Cross Entropy(BCE)**

In [127]:
from numpy import dtype
import torch

pos_weight = torch.tensor(weights, dtype = torch.float32)
pos_weight

tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219])

In [128]:
torch.nn.BCEWithLogitsLoss(
    pos_weight = pos_weight
)

BCEWithLogitsLoss()

In [ ]:
from transformers import Trainer

class WeightedTrainer(Trainer):
    def compute_loss(
        self,
        model,
        inputs,
        return_outputs = False,
        **kwargs,
    ):
        labels = inputs.pop("labels")
        outputs = model(**inputs)

        loss_fct = torch.nn.BCEWithLogitsLoss(
            pos_weight = pos_weight.to(outputs.logits.device)
        )

        loss = loss_fct(
            outputs.logits,
            labels.float()
        )

        return ((loss, outputs) if return_outputs else loss)

### **Converting int values to float**

In [105]:
sample = train_dataset[0]
print(type(sample["labels"][0]))

<class 'float'>

In [106]:
print(train_dataset.features)

{'Text': Value('string'), 'Fear': Value('int64'), 'Anxiety': Value('int64'), 'Panic': Value('int64'), 'Distress': Value('int64'), 'Urgency': Value('int64'), 'Coercion': Value('int64'), 'Aggression': Value('int64'), 'Helplessness': Value('int64'), 'Calm': Value('int64'), '__index_level_0__': Value('int64'), 'input_ids': List(Value('int32')), 'attention_mask': List(Value('int8')), 'labels': List(Value('float64'))}

### **Establishing the model**

In [107]:
from transformers import DistilBertForSequenceClassification

model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels = 9,
    problem_type = "multi_label_classification"
)

Loading weights: 100%|██████████| 100/100 [00:00<00:00, 5000.42it/s]
DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
pre_classifier.weight   | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

### **Preparing the Evaluation for the model**

In [256]:
from sklearn.metrics import (
    f1_score,
    precision_score,
    recall_score,
)

import numpy as np
import torch

In [ ]:
# !pip install transformers[torch]

In [108]:
from transformers import TrainingArguments

training_arguments = TrainingArguments(
    output_dir = "C:/Users/Atharva Nair/kavaach/ml-model/model/kavaach",
    learning_rate = 2e-5,
    per_device_train_batch_size = 16,
    per_device_eval_batch_size = 16,
    num_train_epochs = 3,
)

In [139]:
trainer = WeightedTrainer(
    model = model,
    args = training_arguments,
    train_dataset = train_dataset,
    eval_dataset= test_dataset
)

### **Starting the training**

In [140]:
trainer.train()

Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')

Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.50it/s]

Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.02it/s]

Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.32it/s]

Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.17it/s]

Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.56it/s]

Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.29it/s]

Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.25it/s]

Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.23it/s]

Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.23it/s]

Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.07it/s]

Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.26it/s]

Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.26it/s]

Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.08it/s]

Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.82it/s]

Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.98it/s]

Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.13it/s]

Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.08it/s]

Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.16it/s]

Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.10it/s]

Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.20it/s]

Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.30it/s]

Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.18it/s]

Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.24it/s]

Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.36it/s]

Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')
Current pos_weight:
tensor([3.9263, 1.2427, 3.0497, 0.9641, 1.2328, 1.9259, 1.5164, 1.4067, 0.2219],
       device='cuda:0')

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  3.97it/s]

TrainOutput(global_step=12207, training_loss=0.19791292243833145, metrics={'train_runtime': 2572.4325, 'train_samples_per_second': 75.925, 'train_steps_per_second': 4.745, 'total_flos': 6468925589508096.0, 'train_loss': 0.19791292243833145, 'epoch': 3.0})

In [207]:
trainer.save_model("C:/Users/Atharva Nair/kavaach/ml-model/model/kavaach")
tokenizer.save_pretrained("C:/Users/Atharva Nair/kavaach/ml-model/model/kavaach")

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.64it/s]

('C:/Users/Atharva Nair/kavaach/ml-model/model/kavaach\\tokenizer_config.json',
 'C:/Users/Atharva Nair/kavaach/ml-model/model/kavaach\\tokenizer.json')

In [146]:
# model.eval_loss()

# **Prediction**

In [168]:
from transformers import pipeline

kavaach = pipeline(
    "text-classification",
    model = "C:/Users/Atharva Nair/kavaach/ml-model/model/kavaach",
    tokenizer = tokenizer
)

Loading weights: 100%|██████████| 104/104 [00:00<00:00, 3522.83it/s]

In [167]:
print(model.config.problem_type)
print(model.config.num_labels)
print(model.config.id2label)

multi_label_classification
9
{0: 'LABEL_0', 1: 'LABEL_1', 2: 'LABEL_2', 3: 'LABEL_3', 4: 'LABEL_4', 5: 'LABEL_5', 6: 'LABEL_6', 7: 'LABEL_7', 8: 'LABEL_8'}

In [ ]:
result = kavaach("Someone is following me and I feel unsafe.", top_k = None)
result

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

[{'label': 'LABEL_0', 'score': 0.9630081653594971},
 {'label': 'LABEL_2', 'score': 0.6280001997947693},
 {'label': 'LABEL_1', 'score': 0.2596195936203003},
 {'label': 'LABEL_6', 'score': 0.10665485262870789},
 {'label': 'LABEL_5', 'score': 0.04612131416797638},
 {'label': 'LABEL_3', 'score': 0.02085067704319954},
 {'label': 'LABEL_8', 'score': 0.014618040062487125},
 {'label': 'LABEL_7', 'score': 0.013316411525011063},
 {'label': 'LABEL_4', 'score': 0.004911780823022127}]

In [199]:
for emotion, x in zip(emotion_labels, result):
    print(f"{emotion} \t {round(x['score'],3)*100} % ")

Fear 	 96.3 %
Anxiety 	 62.8 %
Panic 	 26.0 %
Distress 	 10.7 %
Urgency 	 4.6 %
Coercion 	 2.1 %
Aggression 	 1.5 %
Helplessness 	 1.3 %
Calm 	 0.5 %

### **Prediction on val and test datasets and interpretting the output**

### **Prediction on test**

In [257]:
predictions_test = trainer.predict(test_dataset)

Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')

Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')

In [258]:
predictions_test

PredictionOutput(predictions=array([[-7.247109 , -3.6432137, -7.4097047, ..., -3.3950813, -5.691896 ,
         1.1006547],
       [-2.534379 , -4.296842 , -1.9503713, ...,  1.0706897, -4.6156287,
        -3.972796 ],
       [-7.4996114, -5.525476 , -7.5240145, ..., -5.336917 , -6.061453 ,
         2.6619742],
       ...,
       [-7.885786 , -4.6898675, -7.061013 , ..., -3.692306 , -1.545973 ,
        -1.0859756],
       [-3.9766686, -4.514244 , -2.3082123, ..., -3.454922 ,  1.1241364,
        -2.8700671],
       [-5.198546 , -4.395302 , -5.030441 , ..., -4.644777 , -3.269489 ,
         1.0921155]], shape=(8138, 9), dtype=float32), label_ids=array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(8138, 9), dtype=float32), metrics={'test_loss': 0.21849675476551056, 'test_runtime': 27.556, 'test_samples_per_second': 295.326, 'test_steps_per_second': 18.471})

In [260]:
torch.set_printoptions(precision=2, sci_mode=False)
probs_test = torch.sigmoid(torch.tensor(predictions_test.predictions)) * 100
print(probs_test)

tensor([[    0.07,     2.55,     0.06,  ...,     3.24,     0.34,    75.04],
        [    7.35,     1.34,    12.45,  ...,    74.47,     0.98,     1.85],
        [    0.06,     0.40,     0.05,  ...,     0.48,     0.23,    93.47],
        ...,
        [    0.04,     0.91,     0.09,  ...,     2.43,    17.57,    25.24],
        [    1.84,     1.08,     9.04,  ...,     3.06,    75.48,     5.37],
        [    0.55,     1.22,     0.65,  ...,     0.95,     3.66,    74.88]])

In [264]:
pred_test = (probs_test > 0.7).int()
pred_test

tensor([[0, 1, 0,  ..., 1, 0, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        [0, 0, 0,  ..., 0, 0, 1],
        ...,
        [0, 1, 0,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        [0, 1, 0,  ..., 1, 1, 1]], dtype=torch.int32)

In [265]:
from sklearn.metrics import classification_report

print(
    classification_report(
        predictions_test.label_ids,
        pred_test,
        target_names=emotion_labels,
        zero_division=0
    )
)

              precision    recall  f1-score   support

        Fear       0.14      0.95      0.24       254
     Anxiety       0.19      0.96      0.31       896
       Panic       0.14      0.94      0.24       347
    Distress       0.28      0.97      0.43      1154
     Urgency       0.17      0.97      0.30       960
    Coercion       0.14      0.97      0.24       556
  Aggression       0.17      0.98      0.28       712
Helplessness       0.21      0.97      0.34       795
        Calm       0.67      1.00      0.80      5161

   micro avg       0.28      0.98      0.44     10835
   macro avg       0.23      0.97      0.35     10835
weighted avg       0.42      0.98      0.55     10835
 samples avg       0.39      0.99      0.51     10835

### **Running Prediction on the validation set to check precision**

In [237]:
predictions = trainer.predict(val_dataset)

Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')

Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')
Current pos_weight:
tensor([3.93, 1.24, 3.05, 0.96, 1.23, 1.93, 1.52, 1.41, 0.22], device='cuda:0')

In [259]:
torch.set_printoptions(precision=2, sci_mode=False)
probs_val = torch.sigmoid(torch.tensor(predictions.predictions)) * 100
print(probs_val)

tensor([[    0.12,     0.21,     0.09,  ...,     0.18,     0.10,    98.29],
        [    0.10,    25.68,     0.10,  ...,     0.90,     1.49,    25.39],
        [    0.06,    18.06,     0.10,  ...,     3.09,     0.53,    24.87],
        ...,
        [    0.60,     0.40,    14.15,  ...,    97.27,     2.98,     1.11],
        [    0.18,     1.43,     0.06,  ...,     0.22,     0.15,    91.08],
        [    0.03,     6.92,     0.02,  ...,     4.15,     0.55,    47.41]])

In [261]:
pred = (probs_val > 0.7).int()
pred

tensor([[0, 0, 0,  ..., 0, 0, 1],
        [0, 1, 0,  ..., 1, 1, 1],
        [0, 1, 0,  ..., 1, 0, 1],
        ...,
        [0, 0, 1,  ..., 1, 1, 1],
        [0, 1, 0,  ..., 0, 0, 1],
        [0, 1, 0,  ..., 1, 0, 1]], dtype=torch.int32)

In [262]:
from sklearn.metrics import classification_report

print(
    classification_report(
        predictions.label_ids,
        pred,
        target_names=emotion_labels,
        zero_division=0
    )
)

              precision    recall  f1-score   support

        Fear       0.16      0.95      0.27       302
     Anxiety       0.18      0.97      0.31       874
       Panic       0.14      0.96      0.24       366
    Distress       0.28      0.97      0.44      1184
     Urgency       0.17      0.97      0.29       948
    Coercion       0.14      0.95      0.24       568
  Aggression       0.16      0.97      0.27       672
Helplessness       0.21      0.96      0.35       824
        Calm       0.66      1.00      0.80      5115

   micro avg       0.28      0.98      0.44     10853
   macro avg       0.23      0.97      0.36     10853
weighted avg       0.42      0.98      0.55     10853
 samples avg       0.39      0.98      0.51     10853

# **Upgrade**