In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("hate_speech_1829.csv")
data.head(10)

,post_id,timestamp,platform,user_id,text,label,language,preprocessed_text
0,6bcf29c5,2024-07-15 03:26:02,Twitter,user_1947,Quickly city or call score standard want. Thes...,hateful,en,quickly city or call score standard these peop...
1,f91c8e39,2024-01-30 07:34:40,Twitter,user_8255,Thought fund whole me. You are such a dumb!,offensive,en,thought fund whole you are such a
2,5b66edf1,2022-11-24 10:48:27,Twitter,user_3908,Close establish table remember us. You are suc...,offensive,en,close establish table remember you are such a
3,d709cd45,2023-09-26 17:34:44,Twitter,user_1244,Office activity between note analysis series o...,hateful,en,office activity between note analysis series t...
4,b8313a62,2024-03-16 07:56:28,Twitter,user_6006,Attention stay ever international available. Y...,offensive,en,attention stay ever international you are such a
5,203ad96f,2024-09-06 22:19:41,Reddit,user_8865,Republican memory factor capital spend.,neutral,en,republican memory factor capital
6,38aea1c7,2023-03-25 19:02:36,Twitter,user_7128,Team line opportunity actually. These people a...,hateful,en,team line opportunity these people are
7,97ef6076,2022-01-01 11:52:49,Twitter,user_3175,Explain seat young area message message ask. Y...,offensive,en,explain seat young area message message you ar...
8,fdb2e7b1,2022-09-15 14:40:53,Twitter,user_2365,Decide expert customer parent mouth. You are s...,offensive,en,decide expert customer parent you are such a shut
9,6ba442c4,2023-04-19 16:16:08,Reddit,user_5994,Race their hundred international daughter.,neutral,en,race their hundred international

In [3]:
practice = data[["timestamp", "text", "label"]]
practice

,timestamp,text,label
0,2024-07-15 03:26:02,Quickly city or call score standard want. Thes...,hateful
1,2024-01-30 07:34:40,Thought fund whole me. You are such a dumb!,offensive
2,2022-11-24 10:48:27,Close establish table remember us. You are suc...,offensive
3,2023-09-26 17:34:44,Office activity between note analysis series o...,hateful
4,2024-03-16 07:56:28,Attention stay ever international available. Y...,offensive
...,...,...,...
1824,2022-05-24 15:48:02,Just question month dark shoulder board intere...,neutral
1825,2024-05-25 10:48:09,Face measure about up avoid.,neutral
1826,2022-07-22 16:21:48,Cause class American ok. These people are hate!,hateful
1827,2022-03-04 07:36:06,Investment move put loss continue end. You are...,offensive
1828,2023-04-25 03:56:04,Mission one people around. You are such a trash!,offensive

In [4]:
practice.isnull().sum()

timestamp    0
text         0
label        0
dtype: int64

In [5]:
practice["timestamp"] = pd.to_datetime(practice["timestamp"], errors="coerce")
practice["timestamp"] = practice["timestamp"].dt.strftime("%Y-%m-%d")
practice

C:\Users\Atharva Nair\AppData\Local\Temp\ipykernel_32400\3962965477.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  practice["timestamp"] = pd.to_datetime(practice["timestamp"], errors="coerce")
C:\Users\Atharva Nair\AppData\Local\Temp\ipykernel_32400\3962965477.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  practice["timestamp"] = practice["timestamp"].dt.strftime("%Y-%m-%d")

       timestamp                                               text      label
0     2024-07-15  Quickly city or call score standard want. Thes...    hateful
1     2024-01-30        Thought fund whole me. You are such a dumb!  offensive
2     2022-11-24  Close establish table remember us. You are suc...  offensive
3     2023-09-26  Office activity between note analysis series o...    hateful
4     2024-03-16  Attention stay ever international available. Y...  offensive
...          ...                                                ...        ...
1824  2022-05-24  Just question month dark shoulder board intere...    neutral
1825  2024-05-25                       Face measure about up avoid.    neutral
1826  2022-07-22    Cause class American ok. These people are hate!    hateful
1827  2022-03-04  Investment move put loss continue end. You are...  offensive
1828  2023-04-25   Mission one people around. You are such a trash!  offensive

[1829 rows x 3 columns]

In [6]:
import nltk
nltk.download("punkt")

[nltk_data] Downloading package punkt to C:\Users\Atharva
[nltk_data]     Nair\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [7]:
from nltk import word_tokenize, sent_tokenize
practice_text = practice["text"].tolist()

tokenized_text = [word_tokenize(val) for val in practice_text]
tokenized_text

[['Quickly',
  'city',
  'or',
  'call',
  'score',
  'standard',
  'want',
  '.',
  'These',
  'people',
  'are',
  'hate',
  '!'],
 ['Thought',
  'fund',
  'whole',
  'me',
  '.',
  'You',
  'are',
  'such',
  'a',
  'dumb',
  '!'],
 ['Close',
  'establish',
  'table',
  'remember',
  'us',
  '.',
  'You',
  'are',
  'such',
  'a',
  'stupid',
  '!'],
 ['Office',
  'activity',
  'between',
  'note',
  'analysis',
  'series',
  'our',
  '.',
  'These',
  'people',
  'are',
  'plague',
  '!'],
 ['Attention',
  'stay',
  'ever',
  'international',
  'available',
  '.',
  'You',
  'are',
  'such',
  'a',
  'stupid',
  '!'],
 ['Republican', 'memory', 'factor', 'capital', 'spend', '.'],
 ['Team',
  'line',
  'opportunity',
  'actually',
  '.',
  'These',
  'people',
  'are',
  'filthy',
  '!'],
 ['Explain',
  'seat',
  'young',
  'area',
  'message',
  'message',
  'ask',
  '.',
  'You',
  'are',
  'such',
  'a',
  'shut',
  'up',
  '!'],
 ['Decide',
  'expert',
  'customer',
  'parent',
  'mouth',
  '.',
  'You',
  'are',
  'such',
  'a',
  'shut',
  'up',
  '!'],
 ['Race', 'their', 'hundred', 'international', 'daughter', '.'],
 ['Above',
  'try',
  'life',
  'can',
  'community',
  'realize',
  '.',
  'You',
  'are',
  'such',
  'a',
  'shut',
  'up',
  '!'],
 ['Head',
  'white',
  'draw',
  'one',
  'line',
  '.',
  'You',
  'are',
  'such',
  'a',
  'idiot',
  '!'],
 ['Professional', 'strong', 'give', 'nice', 'since', '.'],
 ['Affect',
  'score',
  'thus',
  'practice',
  'understand',
  '.',
  'These',
  'people',
  'are',
  'deport',
  '!'],
 ['Deal',
  'chance',
  'condition',
  'choose',
  'state',
  'though',
  '.',
  'These',
  'people',
  'are',
  'deport',
  '!'],
 ['Important', 'soon', 'training', 'effect', 'quickly', '.'],
 ['Republican', 'three', 'and', 'executive', 'at', 'purpose', '.'],
 ['Among', 'idea', 'center', 'measure', 'eye', '.'],
 ['Message', 'wife', 'leave', 'number', 'truth', '.'],
 ['Painting', 'audience', 'spend', 'nearly', 'sell', 'line', '.'],
 ['Visit', 'fast', 'expect', 'alone', 'position', 'recently', '.'],
 ['Expect', 'force', 'strategy', 'night', 'however', '.'],
 ['Tonight', 'everybody', 'east', 'six', 'simply', '.'],
 ['Prepare',
  'who',
  'wife',
  'stop',
  'week',
  '.',
  'You',
  'are',
  'such',
  'a',
  'dumb',
  '!'],
 ['Arrive',
  'quickly',
  'woman',
  'billion',
  'value',
  '.',
  'You',
  'are',
  'such',
  'a',
  'idiot',
  '!'],
 ['Eat', 'production', 'along', 'character', '.'],
 ['Catch',
  'never',
  'study',
  'claim',
  'west',
  '.',
  'These',
  'people',
  'are',
  'plague',
  '!'],
 ['Reach', 'century', 'close', 'site', '.'],
 ['Common',
  'will',
  'board',
  'back',
  '.',
  'These',
  'people',
  'are',
  'deport',
  '!'],
 ['Company', 'site', 'among', 'right', 'city', 'discover', '.'],
 ['Third',
  'quite',
  'rock',
  'than',
  '.',
  'These',
  'people',
  'are',
  'deport',
  '!'],
 ['Many',
  'top',
  'become',
  'bank',
  'name',
  'north',
  'candidate',
  'attack',
  '.',
  'These',
  'people',
  'are',
  'plague',
  '!'],
 ['Student', 'nature', 'compare', 'report', 'it', '.'],
 ['Down', 'book', 'action', '.'],
 ['May', 'leg', 'ago', 'rate', 'office', '.'],
 ['Leader', 'any', 'instead', 'type', 'thus', '.'],
 ['Share',
  'pretty',
  'power',
  'whole',
  'similar',
  'billion',
  '.',
  'You',
  'are',
  'such',
  'a',
  'shut',
  'up',
  '!'],
 ['Real',
  'alone',
  'public',
  'boy',
  'win',
  'into',
  'challenge',
  '.',
  'You',
  'are',
  'such',
  'a',
  'idiot',
  '!'],
 ['Read',
  'design',
  'outside',
  'race',
  'forget',
  'produce',
  '.',
  'You',
  'are',
  'such',
  'a',
  'idiot',
  '!'],
 ['Single',
  'within',
  'the',
  'choose',
  '.',
  'You',
  'are',
  'such',
  'a',
  'stupid',
  '!'],
 ['Pay',
  'certainly',
  'discover',
  'Congress',
  'push',
  'style',
  '.',
  'You',
  'are',
  'such',
  'a',
  'shut',
  'up',
  '!'],
 ['Argue', 'follow', 'born', 'wide', 'smile', 'those', 'father', 'her', '.'],
 ['Blue', 'service', 'perform', 'take', 'daughter', 'industry', 'almost', '.'],
 ['Discuss', 'energy', 'suffer', '.'],
 ['Safe',
  'professional',
  'focus',
  'interesting',
  'pick',
  'lawyer',
  'agency',
  '.'],
 ['Raise',
  'almost',
  'ever',
  'hard',
  '.',
  'These',
  'people',
  'are',
  'filthy',
  '!'],
 ['All', 'suggest', 'offer', 'Congress', '.'],
 ['Tree', 'generation', 'which', '.'],
 ['Leg',
  'item',
  'class',
  'hospital',
  'community',
  '.',
  'You',
  'are',
  'such',
  'a',
  'dumb',
  '!'],
 ['Me', 'poor', 'throughout', 'difficult', '.'],
 ['Population', 'fund', 'full', 'painting', 'fear', '.'],
 ['Hand',
  'these',
  'free',
  'value',
  'focus',
  '.',
  'These',
  'people',
  'are',
  'filthy',
  '!'],
 ['Where',
  'despite',
  'better',
  '.',
  'These',
  'people',
  'are',
  'disgusting',
  '!'],
 ['Financial',
  'woman',
  'anything',
  'add',
  'thousand',
  '.',
  'You',
  'are',
  'such',
  'a',
  'shut',
  'up',
  '!'],
 ['Unit', 'hold', 'all', 'year', 'response', 'debate', '.'],
 ['Say', 'any', 'special', '.'],
 ['None',
  'quite',
  'last',
  'notice',
  'read',
  'idea',
  '.',
  'You',
  'are',
  'such',
  'a',
  'stupid',
  '!'],
 ['Recently',
  'sister',
  'professional',
  'building',
  'identify',
  'brother',
  'so',
  '.'],
 ['Bad',
  'not',
  'appear',
  'fine',
  'sort',
  'magazine',
  'change',
  '.',
  'These',
  'people',
  'are',
  'hate',
  '!'],
 ['Particularly',
  'century',
  'either',
  'for',
  'watch',
  'also',
  '.',
  'These',
  'people',
  'are',
  'go',
  'back',
  '!'],
 ['Treat',
  'do',
  'fill',
  'look',
  'peace',
  '.',
  'You',
  'are',
  'such',
  'a',
  'trash',
  '!'],
 ['Choose',
  'mother',
  'TV',
  'general',
  '.',
  'You',
  'are',
  'such',
  'a',
  'shut',
  'up',
  '!'],
 ['Protect', 'source', 'control', 'listen', '.'],
 ['Miss', 'surface', 'support', 'country', 'best', 'improve', 'me', '.'],
 ['Owner',
  'street',
  'land',
  'certainly',
  'agency',
  'child',
  'imagine',
  '.',
  'You',
  'are',
  'such',
  'a',
  'shut',
  'up',
  '!'],
 ['Fight', 'enter', 'ahead', 'on', 'turn', '.'],
 ['Camera',
  'loss',
  'common',
  'strategy',
  '.',
  'You',
  'are',
  'such',
  'a',
  'idiot',
  '!'],
 ['System',
  'back',
  'share',
  'kid',
  '.',
  'You',
  'are',
  'such',
  'a',
  'dumb',
  '!'],
 ['May',
  'price',
  'if',
  'information',
  'with',
  '.',
  'You',
  'are',
  'such',
  'a',
  'dumb',
  '!'],
 ['Huge', 'source', 'company', 'whole', 'trouble', 'scene', '.'],
 ['Our',
  'glass',
  'this',
  'dark',
  'by',
  'take',
  '.',
  'These',
  'people',
  'are',
  'disgusting',
  '!'],
 ['Cell',
  'speak',
  'fly',
  'capital',
  'like',
  'least',
  'or',
  '.',
  'You',
  'are',
  'such',
  'a',
  'dumb',
  '!'],
 ['Administration',
  'glass',
  'modern',
  'think',
  'radio',
  '.',
  'You',
  'are',
  'such',
  'a',
  'trash',
  '!'],
 ['Bit', 'purpose', 'important', 'enter', 'go', 'consumer', '.'],
 ['Most', 'bill', 'occur', 'action', 'bar', '.'],
 ['Door', 'dog', 'these', 'four', '.'],
 ['Condition', 'senior', 'safe', 'involve', 'approach', 'need', '.'],
 ['You',
  'organization',
  'catch',
  'capital',
  'look',
  'number',
  'term',
  '.',
  'You',
  'are',
  'such',
  'a',
  'stupid',
  '!'],
 ['Reveal',
  'today',
  'stand',
  'laugh',
  'look',
  'should',
  '.',
  'These',
  'people',
  'are',
  'plague',
  '!'],
 ['Teach',
  'everybody',
  'million',
  'evening',
  'heavy',
  'air',
  'see',
  '.',
  'You',
  'are',
  'such',
  'a',
  'dumb',
  '!'],
 ['Travel', 'response', 'raise', 'in', 'business', '.'],
 ['Newspaper',
  'reflect',
  'close',
  'task',
  'notice',
  '.',
  'You',
  'are',
  'such',
  'a',
  'dumb',
  '!'],
 ['Need',
  'end',
  'senior',
  'learn',
  'water',
  '.',
  'You',
  'are',
  'such',
  'a',
  'idiot',
  '!'],
 ['Than', 'hear', 'customer', 'use', '.'],
 ['News', 'exist', 'majority', 'exactly', 'black', 'month', 'appear', '.'],
 ['Course', 'thing', 'require', 'least', '.'],
 ['Factor', 'plant', 'push', 'left', 'occur', 'seat', 'war', 'describe', '.'],
 ['Day', 'age', 'be', 'year', '.'],
 ['Very',
  'admit',
  'wish',
  'guy',
  'high',
  'plant',
  'many',
  'energy',
  '.',
  'These',
  'people',
  'are',
  'hate',
  '!'],
 ['Son', 'history', 'imagine', 'city', '.'],
 ['Task', 'special', 'us', 'throughout', 'prove', 'detail', 'expect', '.'],
 ['Win', 'how', 'project', 'need', 'number', 'everything', '.'],
 ['Guess',
  'they',
  'third',
  'state',
  '.',
  'These',
  'people',
  'are',
  'deport',
  '!'],
 ['Boy', 'power', 'agreement', 'practice', 'young', 'training', 'make', '.'],
 ['Year',
  'contain',
  'travel',
  'church',
  'anything',
  'raise',
  'agency',
  '.',
  'You',
  'are',
  'such',
  'a',
  'idiot',
  '!'],
 ['Simple',
  'direction',
  'serious',
  'return',
  'accept',
  'popular',
  '.',
  'You',
  'are',
  'such',
  'a',
  'idiot',
  '!'],
 ['Collection', 'better', 'technology', '.'],
 ['Never', 'white', 'list', 'inside', '.'],
 ['Purpose',
  'building',
  'agency',
  'dark',
  'letter',
  'thank',
  '.',
  'You',
  'are',
  'such',
  'a',
  'shut',
  'up',
  '!'],
 ['Need',
  'big',
  'more',
  'defense',
  'green',
  '.',
  'You',
  'are',
  'such',
  'a',
  'shut',
  'up',
  '!'],
 ['Participant',
  'night',
  'natural',
  'city',
  'prove',
  'move',
  'respond',
  '.',
  'These',
  'people',
  'are',
  'go',
  'back',
  '!'],
 ['Deal', 'cultural', 'office', 'both', 'deep', '.'],
 ['Different', 'his', 'economic', '.'],
 ['Ok', 'any', 'population', 'plan', 'rock', 'future', '.'],
 ['Behavior',
  'hot',
  'front',
  'police',
  'serve',
  'everybody',
  '.',
  'These',
  'people',
  'are',
  'deport',
  '!'],
 ['True', 'rock', 'happen', 'again', 'live', 'hair', 'free', '.'],
 ['Back', 'ask', 'maintain', 'might', 'down', '.'],
 ['Place',
  'job',
  'back',
  'teacher',
  'others',
  'product',
  'end',
  'professional',
  '.',
  'You',
  'are',
  'such',
  'a',
  'shut',
  'up',
  '!'],
 ['Gas',
  'support',
  'parent',
  'get',
  '.',
  'You',
  'are',
  'such',
  'a',
  'stupid',
  '!'],
 ['Interesting',
  'table',
  'eat',
  'leave',
  'culture',
  '.',
  'You',
  'are',
  'such',
  'a',
  'trash',
  '!'],
 ['Air', 'guy', 'relationship', 'top', 'seem', 'car', 'know', 'suffer', '.'],
 ['Short', 'cultural', 'however', 'former', 'sense', 'left', 'reflect', '.'],
 ['Traditional', 'budget', 'serious', '.'],
 ['Throw', 'floor', 'cell', 'include', '.'],
 ['Defense', 'art', 'western', 'such', 'wrong', 'bit', '.'],
 ['Deep',
  'hot',
  'their',
  'establish',
  'take',
  '.',
  'You',
  'are',
  'such',
  'a',
  'idiot',
  '!'],
 ['War', 'cold', 'sister', 'alone', 'they', '.'],
 ['Physical', 'city', 'his', '.', 'These', 'people', 'are', 'hate', '!'],
 ['Or', 'five', 'increase', 'card', 'watch', 'significant', '.'],
 ['Similar',
  'maintain',
  'top',
  'simply',
  'experience',
  'foreign',
  'along',
  '.'],
 ['Current', 'executive', 'memory', 'suggest', '.'],
 ['Government', 'quite', 'store', 'ask', 'song', 'event', '.'],
 ['Radio', 'officer', 'step', '.', 'You', 'are', 'such', 'a', 'idiot', '!'],
 ['Fill',
  'cold',
  'simple',
  'level',
  'same',
  'imagine',
  '.',
  'These',
  'people',
  'are',
  'deport',
  '!'],
 ['Site',
  'stop',
  'environmental',
  'wall',
  'until',
  'wish',
  '.',
  'These',
  'people',
  'are',
  'plague',
  '!'],
 ['Trip', 'whether', 'others', '.'],
 ['Now',
  'fine',
  'west',
  'cut',
  'move',
  'site',
  'home',
  'service',
  '.',
  'You',
  'are',
  'such',
  'a',
  'trash',
  '!'],
 ['Person',
  'agent',
  'believe',
  'senior',
  'long',
  'onto',
  'wish',
  '.',
  'You',
  'are',
  'such',
  'a',
  'shut',
  'up',
  '!'],
 ['Girl', 'threat', 'various', 'minute', 'talk', 'defense', 'program', '.'],
 ['Morning', 'every', 'administration', 'really', 'add', 'blood', 'talk', '.'],
 ['Exist',
  'win',
  'what',
  'successful',
  '.',
  'You',
  'are',
  'such',
  'a',
  'dumb',
  '!'],
 ['Behavior',
  'Republican',
  'join',
  'while',
  'interest',
  '.',
  'These',
  'people',
  'are',
  'go',
  'back',
  '!'],
 ['Natural', 'today', 'whether', 'leg', '.'],
 ['Style', 'player', 'to', 'compare', '.'],
 ['Natural', 'political', 'within', 'all', '.'],
 ['Out', 'forward', 'citizen', 'specific', 'both', 'opportunity', 'pay', '.'],
 ['Movement', 'high', 'begin', 'meet', 'make', 'include', 'individual', '.'],
 ['According', 'glass', 'peace', 'hit', 'staff', '.'],
 ['Human', 'seat', 'international', '.'],
 ['Quality',
  'new',
  'nor',
  'let',
  'against',
  '.',
  'You',
  'are',
  'such',
  'a',
  'stupid',
  '!'],
 ['Ahead',
  'worker',
  'rise',
  'particular',
  'no',
  'front',
  '.',
  'You',
  'are',
  'such',
  'a',
  'idiot',
  '!'],
 ['Reveal', 'Congress', 'man', '.'],
 ['Imagine', 'leave', 'like', 'southern', '.'],
 ['Decide', 'how', 'something', 'edge', '.'],
 ['Choice',
  'only',
  'create',
  'trade',
  'media',
  'sense',
  'off',
  '.',
  'These',
  'people',
  'are',
  'filthy',
  '!'],
 ['Office', 'nice', 'try', 'experience', 'kitchen', 'common', '.'],
 ['How', 'environmental', 'story', 'public', 'save', 'start', '.'],
 ['Receive',
  'everybody',
  'hospital',
  'yes',
  '.',
  'These',
  'people',
  'are',
  'filthy',
  '!'],
 ['Drop',
  'whatever',
  'and',
  'despite',
  'individual',
  'response',
  '.',
  'You',
  'are',
  'such',
  'a',
  'trash',
  '!'],
 ['Throw',
  'watch',
  'miss',
  'hard',
  '.',
  'You',
  'are',
  'such',
  'a',
  'shut',
  'up',
  '!'],
 ['Natural',
  'fish',
  'response',
  'director',
  '.',
  'These',
  'people',
  'are',
  'hate',
  '!'],
 ['Education',
  'travel',
  'spring',
  'Democrat',
  'step',
  'least',
  'office',
  '.',
  'These',
  'people',
  'are',
  'disgusting',
  '!'],
 ['Care',
  'whether',
  'PM',
  'yet',
  'parent',
  '.',
  'These',
  'people',
  'are',
  'filthy',
  '!'],
 ['Help', 'let', 'read', 'issue', 'travel', '.'],
 ['Lawyer', 'room', 'foreign', 'fact', 'well', '.'],
 ['Only', 'say', 'lose', '.', 'You', 'are', 'such', 'a', 'stupid', '!'],
 ['Gun', 'season', 'much', 'ask', 'myself', 'Mr', '.'],
 ['View', 'the', 'already', 'billion', '.'],
 ['Least',
  'mother',
  'couple',
  'why',
  'member',
  'president',
  'event',
  '.',
  'You',
  'are',
  'such',
  'a',
  'stupid',
  '!'],
 ['Develop',
  'may',
  'picture',
  'case',
  'call',
  'whom',
  '.',
  'You',
  'are',
  'such',
  'a',
  'shut',
  'up',
  '!'],
 ['Development',
  'majority',
  'thing',
  'phone',
  'thousand',
  'again',
  'center',
  '.'],
 ['Deep',
  'research',
  'consider',
  'clear',
  '.',
  'You',
  'are',
  'such',
  'a',
  'stupid',
  '!'],
 ['Walk',
  'then',
  'study',
  'wall',
  '.',
  'These',
  'people',
  'are',
  'deport',
  '!'],
 ['Risk', 'article', 'hotel', 'civil', 'fly', 'north', '.'],
 ['Happy', 'product', 'wait', 'trial', 'knowledge', 'out', '.'],
 ['Enter',
  'point',
  'reach',
  'near',
  'federal',
  'method',
  'assume',
  '.',
  'These',
  'people',
  'are',
  'plague',
  '!'],
 ['Need',
  'far',
  'expert',
  'car',
  'product',
  'deep',
  '.',
  'These',
  'people',
  'are',
  'go',
  'back',
  '!'],
 ['Pay',
  'religious',
  'against',
  'through',
  '.',
  'You',
  'are',
  'such',
  'a',
  'dumb',
  '!'],
 ['Serve',
  'direction',
  'bit',
  'move',
  'new',
  '.',
  'You',
  'are',
  'such',
  'a',
  'trash',
  '!'],
 ['Property', 'by', 'full', 'choice', 'travel', '.'],
 ['Nation',
  'behind',
  'station',
  'rock',
  'who',
  '.',
  'These',
  'people',
  'are',
  'hate',
  '!'],
 ['This',
  'article',
  'bill',
  'perform',
  'while',
  'him',
  'onto',
  '.',
  'These',
  'people',
  'are',
  'disgusting',
  '!'],
 ['Sense',
  'field',
  'develop',
  'term',
  '.',
  'You',
  'are',
  'such',
  'a',
  'trash',
  '!'],
 ['Area',
  'movie',
  'black',
  'still',
  '.',
  'You',
  'are',
  'such',
  'a',
  'dumb',
  '!'],
 ['Get',
  'risk',
  'anything',
  'seven',
  'general',
  '.',
  'You',
  'are',
  'such',
  'a',
  'stupid',
  '!'],
 ['Individual',
  'happen',
  'relationship',
  'bar',
  'national',
  'we',
  'election',
  'full',
  '.'],
 ['Form',
  'time',
  'surface',
  'gas',
  'music',
  'lose',
  'author',
  'key',
  '.',
  'You',
  'are',
  'such',
  'a',
  'dumb',
  '!'],
 ['Surface', 'billion', 'national', '.'],
 ['Economy', 'manager', 'sit', 'nation', 'down', '.'],
 ['Structure',
  'region',
  'probably',
  'blue',
  'book',
  'brother',
  'finally',
  '.',
  'You',
  'are',
  'such',
  'a',
  'dumb',
  '!'],
 ['Cell', 'capital', 'cell', 'enter', '.'],
 ['Record', 'late', 'answer', 'herself', 'doctor', 'watch', 'thought', '.'],
 ['List',
  'product',
  'development',
  'home',
  'himself',
  '.',
  'These',
  'people',
  'are',
  'filthy',
  '!'],
 ['From',
  'discover',
  'feel',
  'might',
  'house',
  'senior',
  '.',
  'You',
  'are',
  'such',
  'a',
  'trash',
  '!'],
 ['Entire', 'establish', 'affect', 'say', 'rise', '.'],
 ['Itself', 'leader', 'analysis', 'physical', 'cup', 'fear', 'wear', '.'],
 ['Large', 'increase', 'area', '.'],
 ['Task', 'threat', 'still', 'nothing', 'of', '.'],
 ['Old',
  'director',
  'environment',
  'anyone',
  '.',
  'These',
  'people',
  'are',
  'filthy',
  '!'],
 ['Lead', 'on', 'question', 'remember', 'administration', 'leader', '.'],
 ['Class', 'sell', 'management', '.'],
 ['Those',
  'ask',
  'glass',
  'help',
  'material',
  '.',
  'You',
  'are',
  'such',
  'a',
  'stupid',
  '!'],
 ['Position',
  'yes',
  'course',
  'offer',
  'real',
  '.',
  'You',
  'are',
  'such',
  'a',
  'trash',
  '!'],
 ['Work',
  'mention',
  'man',
  'society',
  'worry',
  '.',
  'You',
  'are',
  'such',
  'a',
  'stupid',
  '!'],
 ['Writer', 'certainly', 'check', 'anyone', 'friend', '.'],
 ['Movement',
  'thing',
  'ask',
  'executive',
  'system',
  'training',
  'however',
  '.'],
 ['Effort',
  'civil',
  'party',
  'boy',
  '.',
  'You',
  'are',
  'such',
  'a',
  'trash',
  '!'],
 ['Issue', 'behavior', 'upon', 'me', 'bed', '.'],
 ['Trip',
  'sit',
  'finally',
  'mission',
  'media',
  'listen',
  '.',
  'You',
  'are',
  'such',
  'a',
  'idiot',
  '!'],
 ['Discover',
  'year',
  'into',
  'newspaper',
  'answer',
  '.',
  'You',
  'are',
  'such',
  'a',
  'trash',
  '!'],
 ['Instead',
  'money',
  'difference',
  'eye',
  '.',
  'You',
  'are',
  'such',
  'a',
  'stupid',
  '!'],
 ['Expert', 'same', 'board', 'common', '.'],
 ['Eat',
  'professional',
  'next',
  'parent',
  'increase',
  'American',
  'south',
  '.',
  'These',
  'people',
  'are',
  'plague',
  '!'],
 ['Talk', 'star', 'food', 'program', '.'],
 ['Property',
  'politics',
  'citizen',
  'PM',
  'church',
  'art',
  'cause',
  'answer',
  '.'],
 ['Very',
  'another',
  'anything',
  'bank',
  'article',
  'happen',
  'people',
  '.',
  'These',
  'people',
  'are',
  'plague',
  '!'],
 ['Candidate', 'defense', 'star', 'statement', '.'],
 ['Name', 'trip', 'billion', 'mouth', 'goal', 'through', 'push', '.'],
 ['Space',
  'happen',
  'ask',
  'economic',
  'world',
  'central',
  '.',
  'These',
  'people',
  'are',
  'deport',
  '!'],
 ['That', 'fast', 'particularly', 'nearly', 'ask', '.'],
 ['Sometimes',
  'remember',
  'soldier',
  'throughout',
  'rise',
  'student',
  'condition',
  'though',
  '.'],
 ['Many',
  'hear',
  'study',
  'memory',
  '.',
  'You',
  'are',
  'such',
  'a',
  'trash',
  '!'],
 ['Political', 'race', 'ball', 'too', 'heart', 'treatment', 'admit', '.'],
 ['Relate', 'south', 'school', 'politics', '.'],
 ['Appear',
  'stock',
  'along',
  'school',
  'down',
  '.',
  'These',
  'people',
  'are',
  'go',
  'back',
  '!'],
 ['Never',
  'report',
  'data',
  'building',
  '.',
  'You',
  'are',
  'such',
  'a',
  'idiot',
  '!'],
 ['Drive', 'life', 'prove', 'forward', '.'],
 ['On',
  'manage',
  'ball',
  'bring',
  'heavy',
  'ever',
  '.',
  'You',
  'are',
  'such',
  'a',
  'trash',
  '!'],
 ['Large', 'peace', 'arm', 'walk', '.', 'These', 'people', 'are', 'hate', '!'],
 ['Fall',
  'give',
  'consumer',
  'yard',
  'around',
  'raise',
  '.',
  'You',
  'are',
  'such',
  'a',
  'shut',
  'up',
  '!'],
 ['Probably',

In [8]:
from nltk.tokenize import RegexpTokenizer
tokenizer = RegexpTokenizer(r"\w+")
tokenized_text = [tokenizer.tokenize(val) for val in practice_text]
tokenized_text

[['Quickly',
  'city',
  'or',
  'call',
  'score',
  'standard',
  'want',
  'These',
  'people',
  'are',
  'hate'],
 ['Thought', 'fund', 'whole', 'me', 'You', 'are', 'such', 'a', 'dumb'],
 ['Close',
  'establish',
  'table',
  'remember',
  'us',
  'You',
  'are',
  'such',
  'a',
  'stupid'],
 ['Office',
  'activity',
  'between',
  'note',
  'analysis',
  'series',
  'our',
  'These',
  'people',
  'are',
  'plague'],
 ['Attention',
  'stay',
  'ever',
  'international',
  'available',
  'You',
  'are',
  'such',
  'a',
  'stupid'],
 ['Republican', 'memory', 'factor', 'capital', 'spend'],
 ['Team',
  'line',
  'opportunity',
  'actually',
  'These',
  'people',
  'are',
  'filthy'],
 ['Explain',
  'seat',
  'young',
  'area',
  'message',
  'message',
  'ask',
  'You',
  'are',
  'such',
  'a',
  'shut',
  'up'],
 ['Decide',
  'expert',
  'customer',
  'parent',
  'mouth',
  'You',
  'are',
  'such',
  'a',
  'shut',
  'up'],
 ['Race', 'their', 'hundred', 'international', 'daughter'],
 ['Above',
  'try',
  'life',
  'can',
  'community',
  'realize',
  'You',
  'are',
  'such',
  'a',
  'shut',
  'up'],
 ['Head', 'white', 'draw', 'one', 'line', 'You', 'are', 'such', 'a', 'idiot'],
 ['Professional', 'strong', 'give', 'nice', 'since'],
 ['Affect',
  'score',
  'thus',
  'practice',
  'understand',
  'These',
  'people',
  'are',
  'deport'],
 ['Deal',
  'chance',
  'condition',
  'choose',
  'state',
  'though',
  'These',
  'people',
  'are',
  'deport'],
 ['Important', 'soon', 'training', 'effect', 'quickly'],
 ['Republican', 'three', 'and', 'executive', 'at', 'purpose'],
 ['Among', 'idea', 'center', 'measure', 'eye'],
 ['Message', 'wife', 'leave', 'number', 'truth'],
 ['Painting', 'audience', 'spend', 'nearly', 'sell', 'line'],
 ['Visit', 'fast', 'expect', 'alone', 'position', 'recently'],
 ['Expect', 'force', 'strategy', 'night', 'however'],
 ['Tonight', 'everybody', 'east', 'six', 'simply'],
 ['Prepare', 'who', 'wife', 'stop', 'week', 'You', 'are', 'such', 'a', 'dumb'],
 ['Arrive',
  'quickly',
  'woman',
  'billion',
  'value',
  'You',
  'are',
  'such',
  'a',
  'idiot'],
 ['Eat', 'production', 'along', 'character'],
 ['Catch',
  'never',
  'study',
  'claim',
  'west',
  'These',
  'people',
  'are',
  'plague'],
 ['Reach', 'century', 'close', 'site'],
 ['Common', 'will', 'board', 'back', 'These', 'people', 'are', 'deport'],
 ['Company', 'site', 'among', 'right', 'city', 'discover'],
 ['Third', 'quite', 'rock', 'than', 'These', 'people', 'are', 'deport'],
 ['Many',
  'top',
  'become',
  'bank',
  'name',
  'north',
  'candidate',
  'attack',
  'These',
  'people',
  'are',
  'plague'],
 ['Student', 'nature', 'compare', 'report', 'it'],
 ['Down', 'book', 'action'],
 ['May', 'leg', 'ago', 'rate', 'office'],
 ['Leader', 'any', 'instead', 'type', 'thus'],
 ['Share',
  'pretty',
  'power',
  'whole',
  'similar',
  'billion',
  'You',
  'are',
  'such',
  'a',
  'shut',
  'up'],
 ['Real',
  'alone',
  'public',
  'boy',
  'win',
  'into',
  'challenge',
  'You',
  'are',
  'such',
  'a',
  'idiot'],
 ['Read',
  'design',
  'outside',
  'race',
  'forget',
  'produce',
  'You',
  'are',
  'such',
  'a',
  'idiot'],
 ['Single', 'within', 'the', 'choose', 'You', 'are', 'such', 'a', 'stupid'],
 ['Pay',
  'certainly',
  'discover',
  'Congress',
  'push',
  'style',
  'You',
  'are',
  'such',
  'a',
  'shut',
  'up'],
 ['Argue', 'follow', 'born', 'wide', 'smile', 'those', 'father', 'her'],
 ['Blue', 'service', 'perform', 'take', 'daughter', 'industry', 'almost'],
 ['Discuss', 'energy', 'suffer'],
 ['Safe', 'professional', 'focus', 'interesting', 'pick', 'lawyer', 'agency'],
 ['Raise', 'almost', 'ever', 'hard', 'These', 'people', 'are', 'filthy'],
 ['All', 'suggest', 'offer', 'Congress'],
 ['Tree', 'generation', 'which'],
 ['Leg',
  'item',
  'class',
  'hospital',
  'community',
  'You',
  'are',
  'such',
  'a',
  'dumb'],
 ['Me', 'poor', 'throughout', 'difficult'],
 ['Population', 'fund', 'full', 'painting', 'fear'],
 ['Hand',
  'these',
  'free',
  'value',
  'focus',
  'These',
  'people',
  'are',
  'filthy'],
 ['Where', 'despite', 'better', 'These', 'people', 'are', 'disgusting'],
 ['Financial',
  'woman',
  'anything',
  'add',
  'thousand',
  'You',
  'are',
  'such',
  'a',
  'shut',
  'up'],
 ['Unit', 'hold', 'all', 'year', 'response', 'debate'],
 ['Say', 'any', 'special'],
 ['None',
  'quite',
  'last',
  'notice',
  'read',
  'idea',
  'You',
  'are',
  'such',
  'a',
  'stupid'],
 ['Recently',
  'sister',
  'professional',
  'building',
  'identify',
  'brother',
  'so'],
 ['Bad',
  'not',
  'appear',
  'fine',
  'sort',
  'magazine',
  'change',
  'These',
  'people',
  'are',
  'hate'],
 ['Particularly',
  'century',
  'either',
  'for',
  'watch',
  'also',
  'These',
  'people',
  'are',
  'go',
  'back'],
 ['Treat', 'do', 'fill', 'look', 'peace', 'You', 'are', 'such', 'a', 'trash'],
 ['Choose',
  'mother',
  'TV',
  'general',
  'You',
  'are',
  'such',
  'a',
  'shut',
  'up'],
 ['Protect', 'source', 'control', 'listen'],
 ['Miss', 'surface', 'support', 'country', 'best', 'improve', 'me'],
 ['Owner',
  'street',
  'land',
  'certainly',
  'agency',
  'child',
  'imagine',
  'You',
  'are',
  'such',
  'a',
  'shut',
  'up'],
 ['Fight', 'enter', 'ahead', 'on', 'turn'],
 ['Camera', 'loss', 'common', 'strategy', 'You', 'are', 'such', 'a', 'idiot'],
 ['System', 'back', 'share', 'kid', 'You', 'are', 'such', 'a', 'dumb'],
 ['May',
  'price',
  'if',
  'information',
  'with',
  'You',
  'are',
  'such',
  'a',
  'dumb'],
 ['Huge', 'source', 'company', 'whole', 'trouble', 'scene'],
 ['Our',
  'glass',
  'this',
  'dark',
  'by',
  'take',
  'These',
  'people',
  'are',
  'disgusting'],
 ['Cell',
  'speak',
  'fly',
  'capital',
  'like',
  'least',
  'or',
  'You',
  'are',
  'such',
  'a',
  'dumb'],
 ['Administration',
  'glass',
  'modern',
  'think',
  'radio',
  'You',
  'are',
  'such',
  'a',
  'trash'],
 ['Bit', 'purpose', 'important', 'enter', 'go', 'consumer'],
 ['Most', 'bill', 'occur', 'action', 'bar'],
 ['Door', 'dog', 'these', 'four'],
 ['Condition', 'senior', 'safe', 'involve', 'approach', 'need'],
 ['You',
  'organization',
  'catch',
  'capital',
  'look',
  'number',
  'term',
  'You',
  'are',
  'such',
  'a',
  'stupid'],
 ['Reveal',
  'today',
  'stand',
  'laugh',
  'look',
  'should',
  'These',
  'people',
  'are',
  'plague'],
 ['Teach',
  'everybody',
  'million',
  'evening',
  'heavy',
  'air',
  'see',
  'You',
  'are',
  'such',
  'a',
  'dumb'],
 ['Travel', 'response', 'raise', 'in', 'business'],
 ['Newspaper',
  'reflect',
  'close',
  'task',
  'notice',
  'You',
  'are',
  'such',
  'a',
  'dumb'],
 ['Need',
  'end',
  'senior',
  'learn',
  'water',
  'You',
  'are',
  'such',
  'a',
  'idiot'],
 ['Than', 'hear', 'customer', 'use'],
 ['News', 'exist', 'majority', 'exactly', 'black', 'month', 'appear'],
 ['Course', 'thing', 'require', 'least'],
 ['Factor', 'plant', 'push', 'left', 'occur', 'seat', 'war', 'describe'],
 ['Day', 'age', 'be', 'year'],
 ['Very',
  'admit',
  'wish',
  'guy',
  'high',
  'plant',
  'many',
  'energy',
  'These',
  'people',
  'are',
  'hate'],
 ['Son', 'history', 'imagine', 'city'],
 ['Task', 'special', 'us', 'throughout', 'prove', 'detail', 'expect'],
 ['Win', 'how', 'project', 'need', 'number', 'everything'],
 ['Guess', 'they', 'third', 'state', 'These', 'people', 'are', 'deport'],
 ['Boy', 'power', 'agreement', 'practice', 'young', 'training', 'make'],
 ['Year',
  'contain',
  'travel',
  'church',
  'anything',
  'raise',
  'agency',
  'You',
  'are',
  'such',
  'a',
  'idiot'],
 ['Simple',
  'direction',
  'serious',
  'return',
  'accept',
  'popular',
  'You',
  'are',
  'such',
  'a',
  'idiot'],
 ['Collection', 'better', 'technology'],
 ['Never', 'white', 'list', 'inside'],
 ['Purpose',
  'building',
  'agency',
  'dark',
  'letter',
  'thank',
  'You',
  'are',
  'such',
  'a',
  'shut',
  'up'],
 ['Need',
  'big',
  'more',
  'defense',
  'green',
  'You',
  'are',
  'such',
  'a',
  'shut',
  'up'],
 ['Participant',
  'night',
  'natural',
  'city',
  'prove',
  'move',
  'respond',
  'These',
  'people',
  'are',
  'go',
  'back'],
 ['Deal', 'cultural', 'office', 'both', 'deep'],
 ['Different', 'his', 'economic'],
 ['Ok', 'any', 'population', 'plan', 'rock', 'future'],
 ['Behavior',
  'hot',
  'front',
  'police',
  'serve',
  'everybody',
  'These',
  'people',
  'are',
  'deport'],
 ['True', 'rock', 'happen', 'again', 'live', 'hair', 'free'],
 ['Back', 'ask', 'maintain', 'might', 'down'],
 ['Place',
  'job',
  'back',
  'teacher',
  'others',
  'product',
  'end',
  'professional',
  'You',
  'are',
  'such',
  'a',
  'shut',
  'up'],
 ['Gas', 'support', 'parent', 'get', 'You', 'are', 'such', 'a', 'stupid'],
 ['Interesting',
  'table',
  'eat',
  'leave',
  'culture',
  'You',
  'are',
  'such',
  'a',
  'trash'],
 ['Air', 'guy', 'relationship', 'top', 'seem', 'car', 'know', 'suffer'],
 ['Short', 'cultural', 'however', 'former', 'sense', 'left', 'reflect'],
 ['Traditional', 'budget', 'serious'],
 ['Throw', 'floor', 'cell', 'include'],
 ['Defense', 'art', 'western', 'such', 'wrong', 'bit'],
 ['Deep',
  'hot',
  'their',
  'establish',
  'take',
  'You',
  'are',
  'such',
  'a',
  'idiot'],
 ['War', 'cold', 'sister', 'alone', 'they'],
 ['Physical', 'city', 'his', 'These', 'people', 'are', 'hate'],
 ['Or', 'five', 'increase', 'card', 'watch', 'significant'],
 ['Similar', 'maintain', 'top', 'simply', 'experience', 'foreign', 'along'],
 ['Current', 'executive', 'memory', 'suggest'],
 ['Government', 'quite', 'store', 'ask', 'song', 'event'],
 ['Radio', 'officer', 'step', 'You', 'are', 'such', 'a', 'idiot'],
 ['Fill',
  'cold',
  'simple',
  'level',
  'same',
  'imagine',
  'These',
  'people',
  'are',
  'deport'],
 ['Site',
  'stop',
  'environmental',
  'wall',
  'until',
  'wish',
  'These',
  'people',
  'are',
  'plague'],
 ['Trip', 'whether', 'others'],
 ['Now',
  'fine',
  'west',
  'cut',
  'move',
  'site',
  'home',
  'service',
  'You',
  'are',
  'such',
  'a',
  'trash'],
 ['Person',
  'agent',
  'believe',
  'senior',
  'long',
  'onto',
  'wish',
  'You',
  'are',
  'such',
  'a',
  'shut',
  'up'],
 ['Girl', 'threat', 'various', 'minute', 'talk', 'defense', 'program'],
 ['Morning', 'every', 'administration', 'really', 'add', 'blood', 'talk'],
 ['Exist', 'win', 'what', 'successful', 'You', 'are', 'such', 'a', 'dumb'],
 ['Behavior',
  'Republican',
  'join',
  'while',
  'interest',
  'These',
  'people',
  'are',
  'go',
  'back'],
 ['Natural', 'today', 'whether', 'leg'],
 ['Style', 'player', 'to', 'compare'],
 ['Natural', 'political', 'within', 'all'],
 ['Out', 'forward', 'citizen', 'specific', 'both', 'opportunity', 'pay'],
 ['Movement', 'high', 'begin', 'meet', 'make', 'include', 'individual'],
 ['According', 'glass', 'peace', 'hit', 'staff'],
 ['Human', 'seat', 'international'],
 ['Quality',
  'new',
  'nor',
  'let',
  'against',
  'You',
  'are',
  'such',
  'a',
  'stupid'],
 ['Ahead',
  'worker',
  'rise',
  'particular',
  'no',
  'front',
  'You',
  'are',
  'such',
  'a',
  'idiot'],
 ['Reveal', 'Congress', 'man'],
 ['Imagine', 'leave', 'like', 'southern'],
 ['Decide', 'how', 'something', 'edge'],
 ['Choice',
  'only',
  'create',
  'trade',
  'media',
  'sense',
  'off',
  'These',
  'people',
  'are',
  'filthy'],
 ['Office', 'nice', 'try', 'experience', 'kitchen', 'common'],
 ['How', 'environmental', 'story', 'public', 'save', 'start'],
 ['Receive',
  'everybody',
  'hospital',
  'yes',
  'These',
  'people',
  'are',
  'filthy'],
 ['Drop',
  'whatever',
  'and',
  'despite',
  'individual',
  'response',
  'You',
  'are',
  'such',
  'a',
  'trash'],
 ['Throw', 'watch', 'miss', 'hard', 'You', 'are', 'such', 'a', 'shut', 'up'],
 ['Natural', 'fish', 'response', 'director', 'These', 'people', 'are', 'hate'],
 ['Education',
  'travel',
  'spring',
  'Democrat',
  'step',
  'least',
  'office',
  'These',
  'people',
  'are',
  'disgusting'],
 ['Care',
  'whether',
  'PM',
  'yet',
  'parent',
  'These',
  'people',
  'are',
  'filthy'],
 ['Help', 'let', 'read', 'issue', 'travel'],
 ['Lawyer', 'room', 'foreign', 'fact', 'well'],
 ['Only', 'say', 'lose', 'You', 'are', 'such', 'a', 'stupid'],
 ['Gun', 'season', 'much', 'ask', 'myself', 'Mr'],
 ['View', 'the', 'already', 'billion'],
 ['Least',
  'mother',
  'couple',
  'why',
  'member',
  'president',
  'event',
  'You',
  'are',
  'such',
  'a',
  'stupid'],
 ['Develop',
  'may',
  'picture',
  'case',
  'call',
  'whom',
  'You',
  'are',
  'such',
  'a',
  'shut',
  'up'],
 ['Development', 'majority', 'thing', 'phone', 'thousand', 'again', 'center'],
 ['Deep',
  'research',
  'consider',
  'clear',
  'You',
  'are',
  'such',
  'a',
  'stupid'],
 ['Walk', 'then', 'study', 'wall', 'These', 'people', 'are', 'deport'],
 ['Risk', 'article', 'hotel', 'civil', 'fly', 'north'],
 ['Happy', 'product', 'wait', 'trial', 'knowledge', 'out'],
 ['Enter',
  'point',
  'reach',
  'near',
  'federal',
  'method',
  'assume',
  'These',
  'people',
  'are',
  'plague'],
 ['Need',
  'far',
  'expert',
  'car',
  'product',
  'deep',
  'These',
  'people',
  'are',
  'go',
  'back'],
 ['Pay', 'religious', 'against', 'through', 'You', 'are', 'such', 'a', 'dumb'],
 ['Serve',
  'direction',
  'bit',
  'move',
  'new',
  'You',
  'are',
  'such',
  'a',
  'trash'],
 ['Property', 'by', 'full', 'choice', 'travel'],
 ['Nation',
  'behind',
  'station',
  'rock',
  'who',
  'These',
  'people',
  'are',
  'hate'],
 ['This',
  'article',
  'bill',
  'perform',
  'while',
  'him',
  'onto',
  'These',
  'people',
  'are',
  'disgusting'],
 ['Sense', 'field', 'develop', 'term', 'You', 'are', 'such', 'a', 'trash'],
 ['Area', 'movie', 'black', 'still', 'You', 'are', 'such', 'a', 'dumb'],
 ['Get',
  'risk',
  'anything',
  'seven',
  'general',
  'You',
  'are',
  'such',
  'a',
  'stupid'],
 ['Individual',
  'happen',
  'relationship',
  'bar',
  'national',
  'we',
  'election',
  'full'],
 ['Form',
  'time',
  'surface',
  'gas',
  'music',
  'lose',
  'author',
  'key',
  'You',
  'are',
  'such',
  'a',
  'dumb'],
 ['Surface', 'billion', 'national'],
 ['Economy', 'manager', 'sit', 'nation', 'down'],
 ['Structure',
  'region',
  'probably',
  'blue',
  'book',
  'brother',
  'finally',
  'You',
  'are',
  'such',
  'a',
  'dumb'],
 ['Cell', 'capital', 'cell', 'enter'],
 ['Record', 'late', 'answer', 'herself', 'doctor', 'watch', 'thought'],
 ['List',
  'product',
  'development',
  'home',
  'himself',
  'These',
  'people',
  'are',
  'filthy'],
 ['From',
  'discover',
  'feel',
  'might',
  'house',
  'senior',
  'You',
  'are',
  'such',
  'a',
  'trash'],
 ['Entire', 'establish', 'affect', 'say', 'rise'],
 ['Itself', 'leader', 'analysis', 'physical', 'cup', 'fear', 'wear'],
 ['Large', 'increase', 'area'],
 ['Task', 'threat', 'still', 'nothing', 'of'],
 ['Old',
  'director',
  'environment',
  'anyone',
  'These',
  'people',
  'are',
  'filthy'],
 ['Lead', 'on', 'question', 'remember', 'administration', 'leader'],
 ['Class', 'sell', 'management'],
 ['Those',
  'ask',
  'glass',
  'help',
  'material',
  'You',
  'are',
  'such',
  'a',
  'stupid'],
 ['Position',
  'yes',
  'course',
  'offer',
  'real',
  'You',
  'are',
  'such',
  'a',
  'trash'],
 ['Work',
  'mention',
  'man',
  'society',
  'worry',
  'You',
  'are',
  'such',
  'a',
  'stupid'],
 ['Writer', 'certainly', 'check', 'anyone', 'friend'],
 ['Movement', 'thing', 'ask', 'executive', 'system', 'training', 'however'],
 ['Effort', 'civil', 'party', 'boy', 'You', 'are', 'such', 'a', 'trash'],
 ['Issue', 'behavior', 'upon', 'me', 'bed'],
 ['Trip',
  'sit',
  'finally',
  'mission',
  'media',
  'listen',
  'You',
  'are',
  'such',
  'a',
  'idiot'],
 ['Discover',
  'year',
  'into',
  'newspaper',
  'answer',
  'You',
  'are',
  'such',
  'a',
  'trash'],
 ['Instead',
  'money',
  'difference',
  'eye',
  'You',
  'are',
  'such',
  'a',
  'stupid'],
 ['Expert', 'same', 'board', 'common'],
 ['Eat',
  'professional',
  'next',
  'parent',
  'increase',
  'American',
  'south',
  'These',
  'people',
  'are',
  'plague'],
 ['Talk', 'star', 'food', 'program'],
 ['Property', 'politics', 'citizen', 'PM', 'church', 'art', 'cause', 'answer'],
 ['Very',
  'another',
  'anything',
  'bank',
  'article',
  'happen',
  'people',
  'These',
  'people',
  'are',
  'plague'],
 ['Candidate', 'defense', 'star', 'statement'],
 ['Name', 'trip', 'billion', 'mouth', 'goal', 'through', 'push'],
 ['Space',
  'happen',
  'ask',
  'economic',
  'world',
  'central',
  'These',
  'people',
  'are',
  'deport'],
 ['That', 'fast', 'particularly', 'nearly', 'ask'],
 ['Sometimes',
  'remember',
  'soldier',
  'throughout',
  'rise',
  'student',
  'condition',
  'though'],
 ['Many', 'hear', 'study', 'memory', 'You', 'are', 'such', 'a', 'trash'],
 ['Political', 'race', 'ball', 'too', 'heart', 'treatment', 'admit'],
 ['Relate', 'south', 'school', 'politics'],
 ['Appear',
  'stock',
  'along',
  'school',
  'down',
  'These',
  'people',
  'are',
  'go',
  'back'],
 ['Never', 'report', 'data', 'building', 'You', 'are', 'such', 'a', 'idiot'],
 ['Drive', 'life', 'prove', 'forward'],
 ['On',
  'manage',
  'ball',
  'bring',
  'heavy',
  'ever',
  'You',
  'are',
  'such',
  'a',
  'trash'],
 ['Large', 'peace', 'arm', 'walk', 'These', 'people', 'are', 'hate'],
 ['Fall',
  'give',
  'consumer',
  'yard',
  'around',
  'raise',
  'You',
  'are',
  'such',
  'a',
  'shut',
  'up'],
 ['Probably',
  'factor',
  'pattern',
  'center',
  'You',
  'are',
  'such',
  'a',
  'idiot'],
 ['Hand',
  'although',
  'then',
  'summer',
  'continue',
  'describe',
  'without',
  'beat',
  'These',
  'people',
  'are',
  'go',
  'back'],
 ['Weight', 'manager', 'enough'],
 ['Take', 'whom', 'strategy', 'discuss'],
 ['Others',
  'sense',
  'health',
  'within',
  'party',
  'You',
  'are',
  'such',
  'a',
  'trash'],
 ['Base', 'win', 'our', 'require', 'very'],
 ['Condition',
  'improve',
  'much',
  'deal',
  'third',
  'see',
  'company',
  'These',
  'people',
  'are',
  'hate'],
 ['Per', 'writer', 'street', 'choice', 'really', 'modern', 'be'],
 ['Nature', 'office', 'specific', 'These', 'people', 'are', 'disgusting'],
 ['White', 'first', 'service', 'itself', 'onto', 'blue', 'area', 'later'],
 ['Maybe', 'drug', 'back', 'You', 'are', 'such', 'a', 'shut', 'up'],
 ['Home', 'in', 'control', 'about'],
 ['Have', 'bit', 'operation', 'billion', 'population'],
 ['True', 'find', 'front', 'general', 'These', 'people', 'are', 'hate'],
 ['South', 'customer', 'family', 'final', 'anything', 'say', 'material'],
 ['Court',
  'heavy',
  'recent',
  'year',
  'network',
  'head',
  'These',
  'people',
  'are',
  'hate'],
 ['Tell', 'player', 'message', 'thousand', 'wind'],
 ['Everybody', 'official', 'specific', 'factor', 'yourself'],
 ['Special', 'great', 'worry', 'thousand', 'along', 'point'],
 ['Least',
  'along',
  'event',
  'stuff',
  'compare',
  'wait',
  'You',
  'are',
  'such',
  'a',
  'stupid'],
 ['Particularly',
  'play',
  'manage',
  'tree',
  'ok',
  'gas',
  'You',
  'are',
  'such',
  'a',
  'shut',
  'up'],
 ['Good', 'project', 'win', 'exist'],
 ['Property', 'court', 'Congress', 'These', 'people', 'are', 'go', 'back'],
 ['Action',
  'keep',
  'number',
  'these',
  'everybody',
  'computer',
  'These',
  'people',
  'are',
  'disgusting'],
 ['Four', 'head', 'check', 'hundred'],
 ['Theory', 'magazine', 'card', 'table', 'election', 'matter'],
 ['Yeah',
  'less',
  'rock',
  'police',
  'environmental',
  'You',
  'are',
  'such',
  'a',
  'stupid'],
 ['Wide',
  'street',
  'use',
  'together',
  'factor',
  'during',
  'live',
  'site',
  'These',
  'people',
  'are',
  'hate'],
 ['Your', 'book', 'history'],
 ['Year', 'what', 'writer', 'especially', 'past', 'letter'],
 ['Accept',
  'go',
  'question',
  'high',
  'enough',
  'two',
  'You',
  'are',
  'such',
  'a',
  'trash'],
 ['Small', 'concern', 'area', 'change'],
 ['Investment',
  'meeting',
  'determine',

In [9]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to C:\Users\Atharva
[nltk_data]     Nair\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [10]:
tokenized_text_1 = [[
    words.lower() 
    for words in sentence] 
    for sentence in tokenized_text]
tokenized_text_1

[['quickly',
  'city',
  'or',
  'call',
  'score',
  'standard',
  'want',
  'these',
  'people',
  'are',
  'hate'],
 ['thought', 'fund', 'whole', 'me', 'you', 'are', 'such', 'a', 'dumb'],
 ['close',
  'establish',
  'table',
  'remember',
  'us',
  'you',
  'are',
  'such',
  'a',
  'stupid'],
 ['office',
  'activity',
  'between',
  'note',
  'analysis',
  'series',
  'our',
  'these',
  'people',
  'are',
  'plague'],
 ['attention',
  'stay',
  'ever',
  'international',
  'available',
  'you',
  'are',
  'such',
  'a',
  'stupid'],
 ['republican', 'memory', 'factor', 'capital', 'spend'],
 ['team',
  'line',
  'opportunity',
  'actually',
  'these',
  'people',
  'are',
  'filthy'],
 ['explain',
  'seat',
  'young',
  'area',
  'message',
  'message',
  'ask',
  'you',
  'are',
  'such',
  'a',
  'shut',
  'up'],
 ['decide',
  'expert',
  'customer',
  'parent',
  'mouth',
  'you',
  'are',
  'such',
  'a',
  'shut',
  'up'],
 ['race', 'their', 'hundred', 'international', 'daughter'],
 ['above',
  'try',
  'life',
  'can',
  'community',
  'realize',
  'you',
  'are',
  'such',
  'a',
  'shut',
  'up'],
 ['head', 'white', 'draw', 'one', 'line', 'you', 'are', 'such', 'a', 'idiot'],
 ['professional', 'strong', 'give', 'nice', 'since'],
 ['affect',
  'score',
  'thus',
  'practice',
  'understand',
  'these',
  'people',
  'are',
  'deport'],
 ['deal',
  'chance',
  'condition',
  'choose',
  'state',
  'though',
  'these',
  'people',
  'are',
  'deport'],
 ['important', 'soon', 'training', 'effect', 'quickly'],
 ['republican', 'three', 'and', 'executive', 'at', 'purpose'],
 ['among', 'idea', 'center', 'measure', 'eye'],
 ['message', 'wife', 'leave', 'number', 'truth'],
 ['painting', 'audience', 'spend', 'nearly', 'sell', 'line'],
 ['visit', 'fast', 'expect', 'alone', 'position', 'recently'],
 ['expect', 'force', 'strategy', 'night', 'however'],
 ['tonight', 'everybody', 'east', 'six', 'simply'],
 ['prepare', 'who', 'wife', 'stop', 'week', 'you', 'are', 'such', 'a', 'dumb'],
 ['arrive',
  'quickly',
  'woman',
  'billion',
  'value',
  'you',
  'are',
  'such',
  'a',
  'idiot'],
 ['eat', 'production', 'along', 'character'],
 ['catch',
  'never',
  'study',
  'claim',
  'west',
  'these',
  'people',
  'are',
  'plague'],
 ['reach', 'century', 'close', 'site'],
 ['common', 'will', 'board', 'back', 'these', 'people', 'are', 'deport'],
 ['company', 'site', 'among', 'right', 'city', 'discover'],
 ['third', 'quite', 'rock', 'than', 'these', 'people', 'are', 'deport'],
 ['many',
  'top',
  'become',
  'bank',
  'name',
  'north',
  'candidate',
  'attack',
  'these',
  'people',
  'are',
  'plague'],
 ['student', 'nature', 'compare', 'report', 'it'],
 ['down', 'book', 'action'],
 ['may', 'leg', 'ago', 'rate', 'office'],
 ['leader', 'any', 'instead', 'type', 'thus'],
 ['share',
  'pretty',
  'power',
  'whole',
  'similar',
  'billion',
  'you',
  'are',
  'such',
  'a',
  'shut',
  'up'],
 ['real',
  'alone',
  'public',
  'boy',
  'win',
  'into',
  'challenge',
  'you',
  'are',
  'such',
  'a',
  'idiot'],
 ['read',
  'design',
  'outside',
  'race',
  'forget',
  'produce',
  'you',
  'are',
  'such',
  'a',
  'idiot'],
 ['single', 'within', 'the', 'choose', 'you', 'are', 'such', 'a', 'stupid'],
 ['pay',
  'certainly',
  'discover',
  'congress',
  'push',
  'style',
  'you',
  'are',
  'such',
  'a',
  'shut',
  'up'],
 ['argue', 'follow', 'born', 'wide', 'smile', 'those', 'father', 'her'],
 ['blue', 'service', 'perform', 'take', 'daughter', 'industry', 'almost'],
 ['discuss', 'energy', 'suffer'],
 ['safe', 'professional', 'focus', 'interesting', 'pick', 'lawyer', 'agency'],
 ['raise', 'almost', 'ever', 'hard', 'these', 'people', 'are', 'filthy'],
 ['all', 'suggest', 'offer', 'congress'],
 ['tree', 'generation', 'which'],
 ['leg',
  'item',
  'class',
  'hospital',
  'community',
  'you',
  'are',
  'such',
  'a',
  'dumb'],
 ['me', 'poor', 'throughout', 'difficult'],
 ['population', 'fund', 'full', 'painting', 'fear'],
 ['hand',
  'these',
  'free',
  'value',
  'focus',
  'these',
  'people',
  'are',
  'filthy'],
 ['where', 'despite', 'better', 'these', 'people', 'are', 'disgusting'],
 ['financial',
  'woman',
  'anything',
  'add',
  'thousand',
  'you',
  'are',
  'such',
  'a',
  'shut',
  'up'],
 ['unit', 'hold', 'all', 'year', 'response', 'debate'],
 ['say', 'any', 'special'],
 ['none',
  'quite',
  'last',
  'notice',
  'read',
  'idea',
  'you',
  'are',
  'such',
  'a',
  'stupid'],
 ['recently',
  'sister',
  'professional',
  'building',
  'identify',
  'brother',
  'so'],
 ['bad',
  'not',
  'appear',
  'fine',
  'sort',
  'magazine',
  'change',
  'these',
  'people',
  'are',
  'hate'],
 ['particularly',
  'century',
  'either',
  'for',
  'watch',
  'also',
  'these',
  'people',
  'are',
  'go',
  'back'],
 ['treat', 'do', 'fill', 'look', 'peace', 'you', 'are', 'such', 'a', 'trash'],
 ['choose',
  'mother',
  'tv',
  'general',
  'you',
  'are',
  'such',
  'a',
  'shut',
  'up'],
 ['protect', 'source', 'control', 'listen'],
 ['miss', 'surface', 'support', 'country', 'best', 'improve', 'me'],
 ['owner',
  'street',
  'land',
  'certainly',
  'agency',
  'child',
  'imagine',
  'you',
  'are',
  'such',
  'a',
  'shut',
  'up'],
 ['fight', 'enter', 'ahead', 'on', 'turn'],
 ['camera', 'loss', 'common', 'strategy', 'you', 'are', 'such', 'a', 'idiot'],
 ['system', 'back', 'share', 'kid', 'you', 'are', 'such', 'a', 'dumb'],
 ['may',
  'price',
  'if',
  'information',
  'with',
  'you',
  'are',
  'such',
  'a',
  'dumb'],
 ['huge', 'source', 'company', 'whole', 'trouble', 'scene'],
 ['our',
  'glass',
  'this',
  'dark',
  'by',
  'take',
  'these',
  'people',
  'are',
  'disgusting'],
 ['cell',
  'speak',
  'fly',
  'capital',
  'like',
  'least',
  'or',
  'you',
  'are',
  'such',
  'a',
  'dumb'],
 ['administration',
  'glass',
  'modern',
  'think',
  'radio',
  'you',
  'are',
  'such',
  'a',
  'trash'],
 ['bit', 'purpose', 'important', 'enter', 'go', 'consumer'],
 ['most', 'bill', 'occur', 'action', 'bar'],
 ['door', 'dog', 'these', 'four'],
 ['condition', 'senior', 'safe', 'involve', 'approach', 'need'],
 ['you',
  'organization',
  'catch',
  'capital',
  'look',
  'number',
  'term',
  'you',
  'are',
  'such',
  'a',
  'stupid'],
 ['reveal',
  'today',
  'stand',
  'laugh',
  'look',
  'should',
  'these',
  'people',
  'are',
  'plague'],
 ['teach',
  'everybody',
  'million',
  'evening',
  'heavy',
  'air',
  'see',
  'you',
  'are',
  'such',
  'a',
  'dumb'],
 ['travel', 'response', 'raise', 'in', 'business'],
 ['newspaper',
  'reflect',
  'close',
  'task',
  'notice',
  'you',
  'are',
  'such',
  'a',
  'dumb'],
 ['need',
  'end',
  'senior',
  'learn',
  'water',
  'you',
  'are',
  'such',
  'a',
  'idiot'],
 ['than', 'hear', 'customer', 'use'],
 ['news', 'exist', 'majority', 'exactly', 'black', 'month', 'appear'],
 ['course', 'thing', 'require', 'least'],
 ['factor', 'plant', 'push', 'left', 'occur', 'seat', 'war', 'describe'],
 ['day', 'age', 'be', 'year'],
 ['very',
  'admit',
  'wish',
  'guy',
  'high',
  'plant',
  'many',
  'energy',
  'these',
  'people',
  'are',
  'hate'],
 ['son', 'history', 'imagine', 'city'],
 ['task', 'special', 'us', 'throughout', 'prove', 'detail', 'expect'],
 ['win', 'how', 'project', 'need', 'number', 'everything'],
 ['guess', 'they', 'third', 'state', 'these', 'people', 'are', 'deport'],
 ['boy', 'power', 'agreement', 'practice', 'young', 'training', 'make'],
 ['year',
  'contain',
  'travel',
  'church',
  'anything',
  'raise',
  'agency',
  'you',
  'are',
  'such',
  'a',
  'idiot'],
 ['simple',
  'direction',
  'serious',
  'return',
  'accept',
  'popular',
  'you',
  'are',
  'such',
  'a',
  'idiot'],
 ['collection', 'better', 'technology'],
 ['never', 'white', 'list', 'inside'],
 ['purpose',
  'building',
  'agency',
  'dark',
  'letter',
  'thank',
  'you',
  'are',
  'such',
  'a',
  'shut',
  'up'],
 ['need',
  'big',
  'more',
  'defense',
  'green',
  'you',
  'are',
  'such',
  'a',
  'shut',
  'up'],
 ['participant',
  'night',
  'natural',
  'city',
  'prove',
  'move',
  'respond',
  'these',
  'people',
  'are',
  'go',
  'back'],
 ['deal', 'cultural', 'office', 'both', 'deep'],
 ['different', 'his', 'economic'],
 ['ok', 'any', 'population', 'plan', 'rock', 'future'],
 ['behavior',
  'hot',
  'front',
  'police',
  'serve',
  'everybody',
  'these',
  'people',
  'are',
  'deport'],
 ['true', 'rock', 'happen', 'again', 'live', 'hair', 'free'],
 ['back', 'ask', 'maintain', 'might', 'down'],
 ['place',
  'job',
  'back',
  'teacher',
  'others',
  'product',
  'end',
  'professional',
  'you',
  'are',
  'such',
  'a',
  'shut',
  'up'],
 ['gas', 'support', 'parent', 'get', 'you', 'are', 'such', 'a', 'stupid'],
 ['interesting',
  'table',
  'eat',
  'leave',
  'culture',
  'you',
  'are',
  'such',
  'a',
  'trash'],
 ['air', 'guy', 'relationship', 'top', 'seem', 'car', 'know', 'suffer'],
 ['short', 'cultural', 'however', 'former', 'sense', 'left', 'reflect'],
 ['traditional', 'budget', 'serious'],
 ['throw', 'floor', 'cell', 'include'],
 ['defense', 'art', 'western', 'such', 'wrong', 'bit'],
 ['deep',
  'hot',
  'their',
  'establish',
  'take',
  'you',
  'are',
  'such',
  'a',
  'idiot'],
 ['war', 'cold', 'sister', 'alone', 'they'],
 ['physical', 'city', 'his', 'these', 'people', 'are', 'hate'],
 ['or', 'five', 'increase', 'card', 'watch', 'significant'],
 ['similar', 'maintain', 'top', 'simply', 'experience', 'foreign', 'along'],
 ['current', 'executive', 'memory', 'suggest'],
 ['government', 'quite', 'store', 'ask', 'song', 'event'],
 ['radio', 'officer', 'step', 'you', 'are', 'such', 'a', 'idiot'],
 ['fill',
  'cold',
  'simple',
  'level',
  'same',
  'imagine',
  'these',
  'people',
  'are',
  'deport'],
 ['site',
  'stop',
  'environmental',
  'wall',
  'until',
  'wish',
  'these',
  'people',
  'are',
  'plague'],
 ['trip', 'whether', 'others'],
 ['now',
  'fine',
  'west',
  'cut',
  'move',
  'site',
  'home',
  'service',
  'you',
  'are',
  'such',
  'a',
  'trash'],
 ['person',
  'agent',
  'believe',
  'senior',
  'long',
  'onto',
  'wish',
  'you',
  'are',
  'such',
  'a',
  'shut',
  'up'],
 ['girl', 'threat', 'various', 'minute', 'talk', 'defense', 'program'],
 ['morning', 'every', 'administration', 'really', 'add', 'blood', 'talk'],
 ['exist', 'win', 'what', 'successful', 'you', 'are', 'such', 'a', 'dumb'],
 ['behavior',
  'republican',
  'join',
  'while',
  'interest',
  'these',
  'people',
  'are',
  'go',
  'back'],
 ['natural', 'today', 'whether', 'leg'],
 ['style', 'player', 'to', 'compare'],
 ['natural', 'political', 'within', 'all'],
 ['out', 'forward', 'citizen', 'specific', 'both', 'opportunity', 'pay'],
 ['movement', 'high', 'begin', 'meet', 'make', 'include', 'individual'],
 ['according', 'glass', 'peace', 'hit', 'staff'],
 ['human', 'seat', 'international'],
 ['quality',
  'new',
  'nor',
  'let',
  'against',
  'you',
  'are',
  'such',
  'a',
  'stupid'],
 ['ahead',
  'worker',
  'rise',
  'particular',
  'no',
  'front',
  'you',
  'are',
  'such',
  'a',
  'idiot'],
 ['reveal', 'congress', 'man'],
 ['imagine', 'leave', 'like', 'southern'],
 ['decide', 'how', 'something', 'edge'],
 ['choice',
  'only',
  'create',
  'trade',
  'media',
  'sense',
  'off',
  'these',
  'people',
  'are',
  'filthy'],
 ['office', 'nice', 'try', 'experience', 'kitchen', 'common'],
 ['how', 'environmental', 'story', 'public', 'save', 'start'],
 ['receive',
  'everybody',
  'hospital',
  'yes',
  'these',
  'people',
  'are',
  'filthy'],
 ['drop',
  'whatever',
  'and',
  'despite',
  'individual',
  'response',
  'you',
  'are',
  'such',
  'a',
  'trash'],
 ['throw', 'watch', 'miss', 'hard', 'you', 'are', 'such', 'a', 'shut', 'up'],
 ['natural', 'fish', 'response', 'director', 'these', 'people', 'are', 'hate'],
 ['education',
  'travel',
  'spring',
  'democrat',
  'step',
  'least',
  'office',
  'these',
  'people',
  'are',
  'disgusting'],
 ['care',
  'whether',
  'pm',
  'yet',
  'parent',
  'these',
  'people',
  'are',
  'filthy'],
 ['help', 'let', 'read', 'issue', 'travel'],
 ['lawyer', 'room', 'foreign', 'fact', 'well'],
 ['only', 'say', 'lose', 'you', 'are', 'such', 'a', 'stupid'],
 ['gun', 'season', 'much', 'ask', 'myself', 'mr'],
 ['view', 'the', 'already', 'billion'],
 ['least',
  'mother',
  'couple',
  'why',
  'member',
  'president',
  'event',
  'you',
  'are',
  'such',
  'a',
  'stupid'],
 ['develop',
  'may',
  'picture',
  'case',
  'call',
  'whom',
  'you',
  'are',
  'such',
  'a',
  'shut',
  'up'],
 ['development', 'majority', 'thing', 'phone', 'thousand', 'again', 'center'],
 ['deep',
  'research',
  'consider',
  'clear',
  'you',
  'are',
  'such',
  'a',
  'stupid'],
 ['walk', 'then', 'study', 'wall', 'these', 'people', 'are', 'deport'],
 ['risk', 'article', 'hotel', 'civil', 'fly', 'north'],
 ['happy', 'product', 'wait', 'trial', 'knowledge', 'out'],
 ['enter',
  'point',
  'reach',
  'near',
  'federal',
  'method',
  'assume',
  'these',
  'people',
  'are',
  'plague'],
 ['need',
  'far',
  'expert',
  'car',
  'product',
  'deep',
  'these',
  'people',
  'are',
  'go',
  'back'],
 ['pay', 'religious', 'against', 'through', 'you', 'are', 'such', 'a', 'dumb'],
 ['serve',
  'direction',
  'bit',
  'move',
  'new',
  'you',
  'are',
  'such',
  'a',
  'trash'],
 ['property', 'by', 'full', 'choice', 'travel'],
 ['nation',
  'behind',
  'station',
  'rock',
  'who',
  'these',
  'people',
  'are',
  'hate'],
 ['this',
  'article',
  'bill',
  'perform',
  'while',
  'him',
  'onto',
  'these',
  'people',
  'are',
  'disgusting'],
 ['sense', 'field', 'develop', 'term', 'you', 'are', 'such', 'a', 'trash'],
 ['area', 'movie', 'black', 'still', 'you', 'are', 'such', 'a', 'dumb'],
 ['get',
  'risk',
  'anything',
  'seven',
  'general',
  'you',
  'are',
  'such',
  'a',
  'stupid'],
 ['individual',
  'happen',
  'relationship',
  'bar',
  'national',
  'we',
  'election',
  'full'],
 ['form',
  'time',
  'surface',
  'gas',
  'music',
  'lose',
  'author',
  'key',
  'you',
  'are',
  'such',
  'a',
  'dumb'],
 ['surface', 'billion', 'national'],
 ['economy', 'manager', 'sit', 'nation', 'down'],
 ['structure',
  'region',
  'probably',
  'blue',
  'book',
  'brother',
  'finally',
  'you',
  'are',
  'such',
  'a',
  'dumb'],
 ['cell', 'capital', 'cell', 'enter'],
 ['record', 'late', 'answer', 'herself', 'doctor', 'watch', 'thought'],
 ['list',
  'product',
  'development',
  'home',
  'himself',
  'these',
  'people',
  'are',
  'filthy'],
 ['from',
  'discover',
  'feel',
  'might',
  'house',
  'senior',
  'you',
  'are',
  'such',
  'a',
  'trash'],
 ['entire', 'establish', 'affect', 'say', 'rise'],
 ['itself', 'leader', 'analysis', 'physical', 'cup', 'fear', 'wear'],
 ['large', 'increase', 'area'],
 ['task', 'threat', 'still', 'nothing', 'of'],
 ['old',
  'director',
  'environment',
  'anyone',
  'these',
  'people',
  'are',
  'filthy'],
 ['lead', 'on', 'question', 'remember', 'administration', 'leader'],
 ['class', 'sell', 'management'],
 ['those',
  'ask',
  'glass',
  'help',
  'material',
  'you',
  'are',
  'such',
  'a',
  'stupid'],
 ['position',
  'yes',
  'course',
  'offer',
  'real',
  'you',
  'are',
  'such',
  'a',
  'trash'],
 ['work',
  'mention',
  'man',
  'society',
  'worry',
  'you',
  'are',
  'such',
  'a',
  'stupid'],
 ['writer', 'certainly', 'check', 'anyone', 'friend'],
 ['movement', 'thing', 'ask', 'executive', 'system', 'training', 'however'],
 ['effort', 'civil', 'party', 'boy', 'you', 'are', 'such', 'a', 'trash'],
 ['issue', 'behavior', 'upon', 'me', 'bed'],
 ['trip',
  'sit',
  'finally',
  'mission',
  'media',
  'listen',
  'you',
  'are',
  'such',
  'a',
  'idiot'],
 ['discover',
  'year',
  'into',
  'newspaper',
  'answer',
  'you',
  'are',
  'such',
  'a',
  'trash'],
 ['instead',
  'money',
  'difference',
  'eye',
  'you',
  'are',
  'such',
  'a',
  'stupid'],
 ['expert', 'same', 'board', 'common'],
 ['eat',
  'professional',
  'next',
  'parent',
  'increase',
  'american',
  'south',
  'these',
  'people',
  'are',
  'plague'],
 ['talk', 'star', 'food', 'program'],
 ['property', 'politics', 'citizen', 'pm', 'church', 'art', 'cause', 'answer'],
 ['very',
  'another',
  'anything',
  'bank',
  'article',
  'happen',
  'people',
  'these',
  'people',
  'are',
  'plague'],
 ['candidate', 'defense', 'star', 'statement'],
 ['name', 'trip', 'billion', 'mouth', 'goal', 'through', 'push'],
 ['space',
  'happen',
  'ask',
  'economic',
  'world',
  'central',
  'these',
  'people',
  'are',
  'deport'],
 ['that', 'fast', 'particularly', 'nearly', 'ask'],
 ['sometimes',
  'remember',
  'soldier',
  'throughout',
  'rise',
  'student',
  'condition',
  'though'],
 ['many', 'hear', 'study', 'memory', 'you', 'are', 'such', 'a', 'trash'],
 ['political', 'race', 'ball', 'too', 'heart', 'treatment', 'admit'],
 ['relate', 'south', 'school', 'politics'],
 ['appear',
  'stock',
  'along',
  'school',
  'down',
  'these',
  'people',
  'are',
  'go',
  'back'],
 ['never', 'report', 'data', 'building', 'you', 'are', 'such', 'a', 'idiot'],
 ['drive', 'life', 'prove', 'forward'],
 ['on',
  'manage',
  'ball',
  'bring',
  'heavy',
  'ever',
  'you',
  'are',
  'such',
  'a',
  'trash'],
 ['large', 'peace', 'arm', 'walk', 'these', 'people', 'are', 'hate'],
 ['fall',
  'give',
  'consumer',
  'yard',
  'around',
  'raise',
  'you',
  'are',
  'such',
  'a',
  'shut',
  'up'],
 ['probably',
  'factor',
  'pattern',
  'center',
  'you',
  'are',
  'such',
  'a',
  'idiot'],
 ['hand',
  'although',
  'then',
  'summer',
  'continue',
  'describe',
  'without',
  'beat',
  'these',
  'people',
  'are',
  'go',
  'back'],
 ['weight', 'manager', 'enough'],
 ['take', 'whom', 'strategy', 'discuss'],
 ['others',
  'sense',
  'health',
  'within',
  'party',
  'you',
  'are',
  'such',
  'a',
  'trash'],
 ['base', 'win', 'our', 'require', 'very'],
 ['condition',
  'improve',
  'much',
  'deal',
  'third',
  'see',
  'company',
  'these',
  'people',
  'are',
  'hate'],
 ['per', 'writer', 'street', 'choice', 'really', 'modern', 'be'],
 ['nature', 'office', 'specific', 'these', 'people', 'are', 'disgusting'],
 ['white', 'first', 'service', 'itself', 'onto', 'blue', 'area', 'later'],
 ['maybe', 'drug', 'back', 'you', 'are', 'such', 'a', 'shut', 'up'],
 ['home', 'in', 'control', 'about'],
 ['have', 'bit', 'operation', 'billion', 'population'],
 ['true', 'find', 'front', 'general', 'these', 'people', 'are', 'hate'],
 ['south', 'customer', 'family', 'final', 'anything', 'say', 'material'],
 ['court',
  'heavy',
  'recent',
  'year',
  'network',
  'head',
  'these',
  'people',
  'are',
  'hate'],
 ['tell', 'player', 'message', 'thousand', 'wind'],
 ['everybody', 'official', 'specific', 'factor', 'yourself'],
 ['special', 'great', 'worry', 'thousand', 'along', 'point'],
 ['least',
  'along',
  'event',
  'stuff',
  'compare',
  'wait',
  'you',
  'are',
  'such',
  'a',
  'stupid'],
 ['particularly',
  'play',
  'manage',
  'tree',
  'ok',
  'gas',
  'you',
  'are',
  'such',
  'a',
  'shut',
  'up'],
 ['good', 'project', 'win', 'exist'],
 ['property', 'court', 'congress', 'these', 'people', 'are', 'go', 'back'],
 ['action',
  'keep',
  'number',
  'these',
  'everybody',
  'computer',
  'these',
  'people',
  'are',
  'disgusting'],
 ['four', 'head', 'check', 'hundred'],
 ['theory', 'magazine', 'card', 'table', 'election', 'matter'],
 ['yeah',
  'less',
  'rock',
  'police',
  'environmental',
  'you',
  'are',
  'such',
  'a',
  'stupid'],
 ['wide',
  'street',
  'use',
  'together',
  'factor',
  'during',
  'live',
  'site',
  'these',
  'people',
  'are',
  'hate'],
 ['your', 'book', 'history'],
 ['year', 'what', 'writer', 'especially', 'past', 'letter'],
 ['accept',
  'go',
  'question',
  'high',
  'enough',
  'two',
  'you',
  'are',
  'such',
  'a',
  'trash'],
 ['small', 'concern', 'area', 'change'],
 ['investment',
  'meeting',
  'determine',

In [11]:
from nltk.corpus import stopwords
to_remove = set(stopwords.words('english'))

modified_tokenized_text = [
    [word for word in sentence if word not in to_remove
    ]for sentence in tokenized_text_1] 
modified_tokenized_text

[['quickly', 'city', 'call', 'score', 'standard', 'want', 'people', 'hate'],
 ['thought', 'fund', 'whole', 'dumb'],
 ['close', 'establish', 'table', 'remember', 'us', 'stupid'],
 ['office', 'activity', 'note', 'analysis', 'series', 'people', 'plague'],
 ['attention', 'stay', 'ever', 'international', 'available', 'stupid'],
 ['republican', 'memory', 'factor', 'capital', 'spend'],
 ['team', 'line', 'opportunity', 'actually', 'people', 'filthy'],
 ['explain', 'seat', 'young', 'area', 'message', 'message', 'ask', 'shut'],
 ['decide', 'expert', 'customer', 'parent', 'mouth', 'shut'],
 ['race', 'hundred', 'international', 'daughter'],
 ['try', 'life', 'community', 'realize', 'shut'],
 ['head', 'white', 'draw', 'one', 'line', 'idiot'],
 ['professional', 'strong', 'give', 'nice', 'since'],
 ['affect', 'score', 'thus', 'practice', 'understand', 'people', 'deport'],
 ['deal',
  'chance',
  'condition',
  'choose',
  'state',
  'though',
  'people',
  'deport'],
 ['important', 'soon', 'training', 'effect', 'quickly'],
 ['republican', 'three', 'executive', 'purpose'],
 ['among', 'idea', 'center', 'measure', 'eye'],
 ['message', 'wife', 'leave', 'number', 'truth'],
 ['painting', 'audience', 'spend', 'nearly', 'sell', 'line'],
 ['visit', 'fast', 'expect', 'alone', 'position', 'recently'],
 ['expect', 'force', 'strategy', 'night', 'however'],
 ['tonight', 'everybody', 'east', 'six', 'simply'],
 ['prepare', 'wife', 'stop', 'week', 'dumb'],
 ['arrive', 'quickly', 'woman', 'billion', 'value', 'idiot'],
 ['eat', 'production', 'along', 'character'],
 ['catch', 'never', 'study', 'claim', 'west', 'people', 'plague'],
 ['reach', 'century', 'close', 'site'],
 ['common', 'board', 'back', 'people', 'deport'],
 ['company', 'site', 'among', 'right', 'city', 'discover'],
 ['third', 'quite', 'rock', 'people', 'deport'],
 ['many',
  'top',
  'become',
  'bank',
  'name',
  'north',
  'candidate',
  'attack',
  'people',
  'plague'],
 ['student', 'nature', 'compare', 'report'],
 ['book', 'action'],
 ['may', 'leg', 'ago', 'rate', 'office'],
 ['leader', 'instead', 'type', 'thus'],
 ['share', 'pretty', 'power', 'whole', 'similar', 'billion', 'shut'],
 ['real', 'alone', 'public', 'boy', 'win', 'challenge', 'idiot'],
 ['read', 'design', 'outside', 'race', 'forget', 'produce', 'idiot'],
 ['single', 'within', 'choose', 'stupid'],
 ['pay', 'certainly', 'discover', 'congress', 'push', 'style', 'shut'],
 ['argue', 'follow', 'born', 'wide', 'smile', 'father'],
 ['blue', 'service', 'perform', 'take', 'daughter', 'industry', 'almost'],
 ['discuss', 'energy', 'suffer'],
 ['safe', 'professional', 'focus', 'interesting', 'pick', 'lawyer', 'agency'],
 ['raise', 'almost', 'ever', 'hard', 'people', 'filthy'],
 ['suggest', 'offer', 'congress'],
 ['tree', 'generation'],
 ['leg', 'item', 'class', 'hospital', 'community', 'dumb'],
 ['poor', 'throughout', 'difficult'],
 ['population', 'fund', 'full', 'painting', 'fear'],
 ['hand', 'free', 'value', 'focus', 'people', 'filthy'],
 ['despite', 'better', 'people', 'disgusting'],
 ['financial', 'woman', 'anything', 'add', 'thousand', 'shut'],
 ['unit', 'hold', 'year', 'response', 'debate'],
 ['say', 'special'],
 ['none', 'quite', 'last', 'notice', 'read', 'idea', 'stupid'],
 ['recently', 'sister', 'professional', 'building', 'identify', 'brother'],
 ['bad', 'appear', 'fine', 'sort', 'magazine', 'change', 'people', 'hate'],
 ['particularly',
  'century',
  'either',
  'watch',
  'also',
  'people',
  'go',
  'back'],
 ['treat', 'fill', 'look', 'peace', 'trash'],
 ['choose', 'mother', 'tv', 'general', 'shut'],
 ['protect', 'source', 'control', 'listen'],
 ['miss', 'surface', 'support', 'country', 'best', 'improve'],
 ['owner',
  'street',
  'land',
  'certainly',
  'agency',
  'child',
  'imagine',
  'shut'],
 ['fight', 'enter', 'ahead', 'turn'],
 ['camera', 'loss', 'common', 'strategy', 'idiot'],
 ['system', 'back', 'share', 'kid', 'dumb'],
 ['may', 'price', 'information', 'dumb'],
 ['huge', 'source', 'company', 'whole', 'trouble', 'scene'],
 ['glass', 'dark', 'take', 'people', 'disgusting'],
 ['cell', 'speak', 'fly', 'capital', 'like', 'least', 'dumb'],
 ['administration', 'glass', 'modern', 'think', 'radio', 'trash'],
 ['bit', 'purpose', 'important', 'enter', 'go', 'consumer'],
 ['bill', 'occur', 'action', 'bar'],
 ['door', 'dog', 'four'],
 ['condition', 'senior', 'safe', 'involve', 'approach', 'need'],
 ['organization', 'catch', 'capital', 'look', 'number', 'term', 'stupid'],
 ['reveal', 'today', 'stand', 'laugh', 'look', 'people', 'plague'],
 ['teach', 'everybody', 'million', 'evening', 'heavy', 'air', 'see', 'dumb'],
 ['travel', 'response', 'raise', 'business'],
 ['newspaper', 'reflect', 'close', 'task', 'notice', 'dumb'],
 ['need', 'end', 'senior', 'learn', 'water', 'idiot'],
 ['hear', 'customer', 'use'],
 ['news', 'exist', 'majority', 'exactly', 'black', 'month', 'appear'],
 ['course', 'thing', 'require', 'least'],
 ['factor', 'plant', 'push', 'left', 'occur', 'seat', 'war', 'describe'],
 ['day', 'age', 'year'],
 ['admit', 'wish', 'guy', 'high', 'plant', 'many', 'energy', 'people', 'hate'],
 ['son', 'history', 'imagine', 'city'],
 ['task', 'special', 'us', 'throughout', 'prove', 'detail', 'expect'],
 ['win', 'project', 'need', 'number', 'everything'],
 ['guess', 'third', 'state', 'people', 'deport'],
 ['boy', 'power', 'agreement', 'practice', 'young', 'training', 'make'],
 ['year',
  'contain',
  'travel',
  'church',
  'anything',
  'raise',
  'agency',
  'idiot'],
 ['simple', 'direction', 'serious', 'return', 'accept', 'popular', 'idiot'],
 ['collection', 'better', 'technology'],
 ['never', 'white', 'list', 'inside'],
 ['purpose', 'building', 'agency', 'dark', 'letter', 'thank', 'shut'],
 ['need', 'big', 'defense', 'green', 'shut'],
 ['participant',
  'night',
  'natural',
  'city',
  'prove',
  'move',
  'respond',
  'people',
  'go',
  'back'],
 ['deal', 'cultural', 'office', 'deep'],
 ['different', 'economic'],
 ['ok', 'population', 'plan', 'rock', 'future'],
 ['behavior',
  'hot',
  'front',
  'police',
  'serve',
  'everybody',
  'people',
  'deport'],
 ['true', 'rock', 'happen', 'live', 'hair', 'free'],
 ['back', 'ask', 'maintain', 'might'],
 ['place',
  'job',
  'back',
  'teacher',
  'others',
  'product',
  'end',
  'professional',
  'shut'],
 ['gas', 'support', 'parent', 'get', 'stupid'],
 ['interesting', 'table', 'eat', 'leave', 'culture', 'trash'],
 ['air', 'guy', 'relationship', 'top', 'seem', 'car', 'know', 'suffer'],
 ['short', 'cultural', 'however', 'former', 'sense', 'left', 'reflect'],
 ['traditional', 'budget', 'serious'],
 ['throw', 'floor', 'cell', 'include'],
 ['defense', 'art', 'western', 'wrong', 'bit'],
 ['deep', 'hot', 'establish', 'take', 'idiot'],
 ['war', 'cold', 'sister', 'alone'],
 ['physical', 'city', 'people', 'hate'],
 ['five', 'increase', 'card', 'watch', 'significant'],
 ['similar', 'maintain', 'top', 'simply', 'experience', 'foreign', 'along'],
 ['current', 'executive', 'memory', 'suggest'],
 ['government', 'quite', 'store', 'ask', 'song', 'event'],
 ['radio', 'officer', 'step', 'idiot'],
 ['fill', 'cold', 'simple', 'level', 'imagine', 'people', 'deport'],
 ['site', 'stop', 'environmental', 'wall', 'wish', 'people', 'plague'],
 ['trip', 'whether', 'others'],
 ['fine', 'west', 'cut', 'move', 'site', 'home', 'service', 'trash'],
 ['person', 'agent', 'believe', 'senior', 'long', 'onto', 'wish', 'shut'],
 ['girl', 'threat', 'various', 'minute', 'talk', 'defense', 'program'],
 ['morning', 'every', 'administration', 'really', 'add', 'blood', 'talk'],
 ['exist', 'win', 'successful', 'dumb'],
 ['behavior', 'republican', 'join', 'interest', 'people', 'go', 'back'],
 ['natural', 'today', 'whether', 'leg'],
 ['style', 'player', 'compare'],
 ['natural', 'political', 'within'],
 ['forward', 'citizen', 'specific', 'opportunity', 'pay'],
 ['movement', 'high', 'begin', 'meet', 'make', 'include', 'individual'],
 ['according', 'glass', 'peace', 'hit', 'staff'],
 ['human', 'seat', 'international'],
 ['quality', 'new', 'let', 'stupid'],
 ['ahead', 'worker', 'rise', 'particular', 'front', 'idiot'],
 ['reveal', 'congress', 'man'],
 ['imagine', 'leave', 'like', 'southern'],
 ['decide', 'something', 'edge'],
 ['choice', 'create', 'trade', 'media', 'sense', 'people', 'filthy'],
 ['office', 'nice', 'try', 'experience', 'kitchen', 'common'],
 ['environmental', 'story', 'public', 'save', 'start'],
 ['receive', 'everybody', 'hospital', 'yes', 'people', 'filthy'],
 ['drop', 'whatever', 'despite', 'individual', 'response', 'trash'],
 ['throw', 'watch', 'miss', 'hard', 'shut'],
 ['natural', 'fish', 'response', 'director', 'people', 'hate'],
 ['education',
  'travel',
  'spring',
  'democrat',
  'step',
  'least',
  'office',
  'people',
  'disgusting'],
 ['care', 'whether', 'pm', 'yet', 'parent', 'people', 'filthy'],
 ['help', 'let', 'read', 'issue', 'travel'],
 ['lawyer', 'room', 'foreign', 'fact', 'well'],
 ['say', 'lose', 'stupid'],
 ['gun', 'season', 'much', 'ask', 'mr'],
 ['view', 'already', 'billion'],
 ['least', 'mother', 'couple', 'member', 'president', 'event', 'stupid'],
 ['develop', 'may', 'picture', 'case', 'call', 'shut'],
 ['development', 'majority', 'thing', 'phone', 'thousand', 'center'],
 ['deep', 'research', 'consider', 'clear', 'stupid'],
 ['walk', 'study', 'wall', 'people', 'deport'],
 ['risk', 'article', 'hotel', 'civil', 'fly', 'north'],
 ['happy', 'product', 'wait', 'trial', 'knowledge'],
 ['enter',
  'point',
  'reach',
  'near',
  'federal',
  'method',
  'assume',
  'people',
  'plague'],
 ['need', 'far', 'expert', 'car', 'product', 'deep', 'people', 'go', 'back'],
 ['pay', 'religious', 'dumb'],
 ['serve', 'direction', 'bit', 'move', 'new', 'trash'],
 ['property', 'full', 'choice', 'travel'],
 ['nation', 'behind', 'station', 'rock', 'people', 'hate'],
 ['article', 'bill', 'perform', 'onto', 'people', 'disgusting'],
 ['sense', 'field', 'develop', 'term', 'trash'],
 ['area', 'movie', 'black', 'still', 'dumb'],
 ['get', 'risk', 'anything', 'seven', 'general', 'stupid'],
 ['individual',
  'happen',
  'relationship',
  'bar',
  'national',
  'election',
  'full'],
 ['form', 'time', 'surface', 'gas', 'music', 'lose', 'author', 'key', 'dumb'],
 ['surface', 'billion', 'national'],
 ['economy', 'manager', 'sit', 'nation'],
 ['structure',
  'region',
  'probably',
  'blue',
  'book',
  'brother',
  'finally',
  'dumb'],
 ['cell', 'capital', 'cell', 'enter'],
 ['record', 'late', 'answer', 'doctor', 'watch', 'thought'],
 ['list', 'product', 'development', 'home', 'people', 'filthy'],
 ['discover', 'feel', 'might', 'house', 'senior', 'trash'],
 ['entire', 'establish', 'affect', 'say', 'rise'],
 ['leader', 'analysis', 'physical', 'cup', 'fear', 'wear'],
 ['large', 'increase', 'area'],
 ['task', 'threat', 'still', 'nothing'],
 ['old', 'director', 'environment', 'anyone', 'people', 'filthy'],
 ['lead', 'question', 'remember', 'administration', 'leader'],
 ['class', 'sell', 'management'],
 ['ask', 'glass', 'help', 'material', 'stupid'],
 ['position', 'yes', 'course', 'offer', 'real', 'trash'],
 ['work', 'mention', 'man', 'society', 'worry', 'stupid'],
 ['writer', 'certainly', 'check', 'anyone', 'friend'],
 ['movement', 'thing', 'ask', 'executive', 'system', 'training', 'however'],
 ['effort', 'civil', 'party', 'boy', 'trash'],
 ['issue', 'behavior', 'upon', 'bed'],
 ['trip', 'sit', 'finally', 'mission', 'media', 'listen', 'idiot'],
 ['discover', 'year', 'newspaper', 'answer', 'trash'],
 ['instead', 'money', 'difference', 'eye', 'stupid'],
 ['expert', 'board', 'common'],
 ['eat',
  'professional',
  'next',
  'parent',
  'increase',
  'american',
  'south',
  'people',
  'plague'],
 ['talk', 'star', 'food', 'program'],
 ['property', 'politics', 'citizen', 'pm', 'church', 'art', 'cause', 'answer'],
 ['another',
  'anything',
  'bank',
  'article',
  'happen',
  'people',
  'people',
  'plague'],
 ['candidate', 'defense', 'star', 'statement'],
 ['name', 'trip', 'billion', 'mouth', 'goal', 'push'],
 ['space',
  'happen',
  'ask',
  'economic',
  'world',
  'central',
  'people',
  'deport'],
 ['fast', 'particularly', 'nearly', 'ask'],
 ['sometimes',
  'remember',
  'soldier',
  'throughout',
  'rise',
  'student',
  'condition',
  'though'],
 ['many', 'hear', 'study', 'memory', 'trash'],
 ['political', 'race', 'ball', 'heart', 'treatment', 'admit'],
 ['relate', 'south', 'school', 'politics'],
 ['appear', 'stock', 'along', 'school', 'people', 'go', 'back'],
 ['never', 'report', 'data', 'building', 'idiot'],
 ['drive', 'life', 'prove', 'forward'],
 ['manage', 'ball', 'bring', 'heavy', 'ever', 'trash'],
 ['large', 'peace', 'arm', 'walk', 'people', 'hate'],
 ['fall', 'give', 'consumer', 'yard', 'around', 'raise', 'shut'],
 ['probably', 'factor', 'pattern', 'center', 'idiot'],
 ['hand',
  'although',
  'summer',
  'continue',
  'describe',
  'without',
  'beat',
  'people',
  'go',
  'back'],
 ['weight', 'manager', 'enough'],
 ['take', 'strategy', 'discuss'],
 ['others', 'sense', 'health', 'within', 'party', 'trash'],
 ['base', 'win', 'require'],
 ['condition',
  'improve',
  'much',
  'deal',
  'third',
  'see',
  'company',
  'people',
  'hate'],
 ['per', 'writer', 'street', 'choice', 'really', 'modern'],
 ['nature', 'office', 'specific', 'people', 'disgusting'],
 ['white', 'first', 'service', 'onto', 'blue', 'area', 'later'],
 ['maybe', 'drug', 'back', 'shut'],
 ['home', 'control'],
 ['bit', 'operation', 'billion', 'population'],
 ['true', 'find', 'front', 'general', 'people', 'hate'],
 ['south', 'customer', 'family', 'final', 'anything', 'say', 'material'],
 ['court', 'heavy', 'recent', 'year', 'network', 'head', 'people', 'hate'],
 ['tell', 'player', 'message', 'thousand', 'wind'],
 ['everybody', 'official', 'specific', 'factor'],
 ['special', 'great', 'worry', 'thousand', 'along', 'point'],
 ['least', 'along', 'event', 'stuff', 'compare', 'wait', 'stupid'],
 ['particularly', 'play', 'manage', 'tree', 'ok', 'gas', 'shut'],
 ['good', 'project', 'win', 'exist'],
 ['property', 'court', 'congress', 'people', 'go', 'back'],
 ['action', 'keep', 'number', 'everybody', 'computer', 'people', 'disgusting'],
 ['four', 'head', 'check', 'hundred'],
 ['theory', 'magazine', 'card', 'table', 'election', 'matter'],
 ['yeah', 'less', 'rock', 'police', 'environmental', 'stupid'],
 ['wide',
  'street',
  'use',
  'together',
  'factor',
  'live',
  'site',
  'people',
  'hate'],
 ['book', 'history'],
 ['year', 'writer', 'especially', 'past', 'letter'],
 ['accept', 'go', 'question', 'high', 'enough', 'two', 'trash'],
 ['small', 'concern', 'area', 'change'],
 ['investment',
  'meeting',
  'determine',
  'hear',
  'actually',
  'seem',
  'owner',
  'everyone',
  'trash'],
 ['cell', 'cell', 'interview', 'city', 'security', 'people', 'go', 'back'],
 ['church', 'debate', 'risk', 'wear'],
 ['face', 'program', 'fill', 'military', 'lose', 'pull', 'consumer'],
 ['including', 'authority', 'practice', 'research', 'quite', 'dumb'],
 ['carry', 'able', 'point', 'smile', 'produce', 'well'],
 ['need', 'improve', 'war'],
 ['avoid', 'court', 'drive'],
 ['general', 'two', 'dinner', 'evening', 'environmental', 'dumb'],
 ['produce', 'green', 'civil', 'expert', 'people', 'filthy'],
 ['old', 'marriage', 'computer', 'moment', 'money', 'stupid'],
 ['cut', 'easy', 'rather', 'leg', 'dumb'],
 ['thus', 'near', 'share'],
 ['far', 'cost', 'sometimes', 'decision'],
 ['enough', 'end', 'summer', 'human', 'describe', 'everything', 'indicate'],
 ['hour',
  'memory',
  'raise',
  'report',
  'maybe',
  'analysis',
  'people',
  'disgusting'],
 ['age', 'trouble', 'character', 'people', 'hate'],
 ['speak', 'red', 'enough'],
 ['fill', 'scientist', 'action', 'language', 'people', 'disgusting'],
 ['beyond', 'knowledge', 'moment'],
 ['difference', 'something', 'keep', 'interview'],
 ['agreement', 'really', 'case', 'size', 'thus', 'long', 'year', 'manager'],
 ['professional',
  'pm',
  'edge',
  'hard',
  'might',
  'specific',
  'meeting',
  'people',
  'plague'],
 ['boy', 'raise', 'throw', 'effort', 'history', 'mother', 'big', 'idiot'],
 ['teacher', 'bad', 'market', 'long', 'reflect', 'game', 'yet', 'sit'],
 ['media', 'white', 'listen', 'dog', 'people', 'disgusting'],
 ['police', 'factor', 'design', 'trash'],
 ['material', 'sense', 'practice', 'put', 'hand', 'get', 'career'],
 ['plant', 'listen', 'marriage', 'worker', 'main', 'door'],
 ['dog', 'tough', 'including'],
 ['another', 'skin', 'stupid'],
 ['score', 'society', 'east', 'everyone', 'shut'],
 ['lose', 'edge', 'save', 'lawyer', 'idiot'],
 ['week', 'full', 'agency', 'media', 'total', 'cultural'],
 ['though', 'indeed', 'shut'],
 ['popular', 'management', 'whatever', 'teacher'],
 ['fine', 'resource', 'concern', 'hear', 'leg', 'around', 'forget'],
 ['voice', 'two', 'leg', 'maintain', 'character'],
 ['quite', 'building', 'middle', 'wear'],
 ['special', 'might', 'program', 'back', 'national', 'sport'],
 ['behind', 'protect', 'perform', 'stupid'],
 ['green', 'activity', 'step', 'focus', 'try'],
 ['never', 'modern', 'recent', 'new', 'health', 'trouble', 'number'],
 ['million', 'risk', 'consider', 'safe', 'security'],
 ['everybody', 'language', 'behind', 'according', 'campaign', 'know'],
 ['old', 'company', 'station', 'idiot'],
 ['growth', 'school', 'team'],
 ['civil', 'base', 'ability', 'generation', 'set'],
 ['gun', 'soon', 'consumer', 'shake', 'sometimes', 'national'],
 ['stuff', 'memory', 'low', 'people', 'hate'],
 ['foot', 'seat', 'capital', 'people', 'hate'],
 ['send',
  'management',
  'detail',
  'throw',
  'near',
  'person',
  'glass',
  'cause',
  'idiot'],
 ['use', 'product', 'tree', 'nice'],
 ['room', 'trip', 'instead', 'thing', 'perform', 'catch', 'stupid'],
 ['ahead', 'grow', 'everybody', 'success', 'body'],
 ['adult', 'research', 'record', 'cover', 'people', 'deport'],
 ['toward', 'huge', 'line', 'school', 'cost', 'far', 'politics'],
 ['board', 'role', 'note', 'sense', 'black', 'official'],
 ['occur', 'mind', 'perhaps', 'worker', 'adult'],
 ['since', 'somebody', 'final'],
 ['somebody', 'every', 'next', 'stupid'],
 ['pay', 'stand', 'family'],
 ['small', 'cost', 'citizen', 'third', 'occur'],
 ['cost', 'little', 'market', 'challenge', 'feeling'],
 ['little', 'age', 'use', 'yard', 'dark', 'best', 'people', 'go', 'back'],
 ['produce', 'name', 'head', 'half', 'near', 'night', 'people', 'go', 'back'],
 ['majority', 'environment', 'reach', 'put'],
 ['radio', 'run', 'clear', 'right', 'increase', 'mission', 'stupid'],
 ['guy', 'visit', 'suffer', 'large'],
 ['wait', 'yard', 'range', 'practice', 'dumb'],
 ['beyond', 'keep', 'fall'],
 ['skill', 'laugh', 'certain'],
 ['always', 'stupid'],
 ['family', 'buy', 'set'],
 ['night', 'board', 'gun', 'minute'],
 ['life', 'identify', 'move', 'story', 'certain', 'scene', 'stupid'],
 ['deal',
  'within',
  'artist',
  'part',
  'hot',
  'order',
  'bad',
  'player',
  'idiot'],
 ['might', 'car', 'receive', 'political', 'address', 'cup'],
 ['none',
  'participant',
  'agency',
  'mother',
  'recently',
  'job',
  'performance',
  'people',
  'disgusting'],
 ['ever', 'hour', 'idiot'],
 ['research', 'worker', 'candidate', 'number', 'watch', 'dumb'],
 ['guy', 'involve'],
 ['box', 'shake', 'national', 'people', 'disgusting'],
 ['yeah', 'bad', 'sport', 'explain'],
 ['middle', 'production', 'strong', 'act', 'order', 'provide', 'idiot'],
 ['plan', 'low', 'move', 'man', 'action', 'rich'],
 ['discuss', 'situation', 'seven', 'medical', 'edge', 'lead', 'shut'],
 ['note', 'congress', 'approach', 'according', 'level', 'risk'],
 ['magazine', 'rather', 'finish', 'soldier', 'effect', 'stupid'],
 ['fast', 'understand', 'possible', 'girl', 'let', 'shut'],
 ['better', 'wear', 'industry', 'north', 'respond', 'dumb'],
 ['eight', 'talk', 'candidate', 'dumb'],
 ['might', 'available', 'position', 'may'],
 ['make', 'worry', 'amount', 'glass', 'section', 'trash'],
 ['perform', 'offer', 'sister', 'dumb'],
 ['fall', 'science', 'hair', 'forget', 'able'],
 ['like',
  'list',
  'analysis',
  'relationship',
  'situation',
  'financial',
  'heart'],
 ['office', 'vote', 'people', 'disgusting'],

In [12]:
nltk.download("wordnet")

[nltk_data] Downloading package wordnet to C:\Users\Atharva
[nltk_data]     Nair\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [13]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

lemmatized_text = [
    [lemmatizer.lemmatize(val) 
    for val in sentence]
    for sentence in modified_tokenized_text]

lemmatized_text

[['quickly', 'city', 'call', 'score', 'standard', 'want', 'people', 'hate'],
 ['thought', 'fund', 'whole', 'dumb'],
 ['close', 'establish', 'table', 'remember', 'u', 'stupid'],
 ['office', 'activity', 'note', 'analysis', 'series', 'people', 'plague'],
 ['attention', 'stay', 'ever', 'international', 'available', 'stupid'],
 ['republican', 'memory', 'factor', 'capital', 'spend'],
 ['team', 'line', 'opportunity', 'actually', 'people', 'filthy'],
 ['explain', 'seat', 'young', 'area', 'message', 'message', 'ask', 'shut'],
 ['decide', 'expert', 'customer', 'parent', 'mouth', 'shut'],
 ['race', 'hundred', 'international', 'daughter'],
 ['try', 'life', 'community', 'realize', 'shut'],
 ['head', 'white', 'draw', 'one', 'line', 'idiot'],
 ['professional', 'strong', 'give', 'nice', 'since'],
 ['affect', 'score', 'thus', 'practice', 'understand', 'people', 'deport'],
 ['deal',
  'chance',
  'condition',
  'choose',
  'state',
  'though',
  'people',
  'deport'],
 ['important', 'soon', 'training', 'effect', 'quickly'],
 ['republican', 'three', 'executive', 'purpose'],
 ['among', 'idea', 'center', 'measure', 'eye'],
 ['message', 'wife', 'leave', 'number', 'truth'],
 ['painting', 'audience', 'spend', 'nearly', 'sell', 'line'],
 ['visit', 'fast', 'expect', 'alone', 'position', 'recently'],
 ['expect', 'force', 'strategy', 'night', 'however'],
 ['tonight', 'everybody', 'east', 'six', 'simply'],
 ['prepare', 'wife', 'stop', 'week', 'dumb'],
 ['arrive', 'quickly', 'woman', 'billion', 'value', 'idiot'],
 ['eat', 'production', 'along', 'character'],
 ['catch', 'never', 'study', 'claim', 'west', 'people', 'plague'],
 ['reach', 'century', 'close', 'site'],
 ['common', 'board', 'back', 'people', 'deport'],
 ['company', 'site', 'among', 'right', 'city', 'discover'],
 ['third', 'quite', 'rock', 'people', 'deport'],
 ['many',
  'top',
  'become',
  'bank',
  'name',
  'north',
  'candidate',
  'attack',
  'people',
  'plague'],
 ['student', 'nature', 'compare', 'report'],
 ['book', 'action'],
 ['may', 'leg', 'ago', 'rate', 'office'],
 ['leader', 'instead', 'type', 'thus'],
 ['share', 'pretty', 'power', 'whole', 'similar', 'billion', 'shut'],
 ['real', 'alone', 'public', 'boy', 'win', 'challenge', 'idiot'],
 ['read', 'design', 'outside', 'race', 'forget', 'produce', 'idiot'],
 ['single', 'within', 'choose', 'stupid'],
 ['pay', 'certainly', 'discover', 'congress', 'push', 'style', 'shut'],
 ['argue', 'follow', 'born', 'wide', 'smile', 'father'],
 ['blue', 'service', 'perform', 'take', 'daughter', 'industry', 'almost'],
 ['discus', 'energy', 'suffer'],
 ['safe', 'professional', 'focus', 'interesting', 'pick', 'lawyer', 'agency'],
 ['raise', 'almost', 'ever', 'hard', 'people', 'filthy'],
 ['suggest', 'offer', 'congress'],
 ['tree', 'generation'],
 ['leg', 'item', 'class', 'hospital', 'community', 'dumb'],
 ['poor', 'throughout', 'difficult'],
 ['population', 'fund', 'full', 'painting', 'fear'],
 ['hand', 'free', 'value', 'focus', 'people', 'filthy'],
 ['despite', 'better', 'people', 'disgusting'],
 ['financial', 'woman', 'anything', 'add', 'thousand', 'shut'],
 ['unit', 'hold', 'year', 'response', 'debate'],
 ['say', 'special'],
 ['none', 'quite', 'last', 'notice', 'read', 'idea', 'stupid'],
 ['recently', 'sister', 'professional', 'building', 'identify', 'brother'],
 ['bad', 'appear', 'fine', 'sort', 'magazine', 'change', 'people', 'hate'],
 ['particularly',
  'century',
  'either',
  'watch',
  'also',
  'people',
  'go',
  'back'],
 ['treat', 'fill', 'look', 'peace', 'trash'],
 ['choose', 'mother', 'tv', 'general', 'shut'],
 ['protect', 'source', 'control', 'listen'],
 ['miss', 'surface', 'support', 'country', 'best', 'improve'],
 ['owner',
  'street',
  'land',
  'certainly',
  'agency',
  'child',
  'imagine',
  'shut'],
 ['fight', 'enter', 'ahead', 'turn'],
 ['camera', 'loss', 'common', 'strategy', 'idiot'],
 ['system', 'back', 'share', 'kid', 'dumb'],
 ['may', 'price', 'information', 'dumb'],
 ['huge', 'source', 'company', 'whole', 'trouble', 'scene'],
 ['glass', 'dark', 'take', 'people', 'disgusting'],
 ['cell', 'speak', 'fly', 'capital', 'like', 'least', 'dumb'],
 ['administration', 'glass', 'modern', 'think', 'radio', 'trash'],
 ['bit', 'purpose', 'important', 'enter', 'go', 'consumer'],
 ['bill', 'occur', 'action', 'bar'],
 ['door', 'dog', 'four'],
 ['condition', 'senior', 'safe', 'involve', 'approach', 'need'],
 ['organization', 'catch', 'capital', 'look', 'number', 'term', 'stupid'],
 ['reveal', 'today', 'stand', 'laugh', 'look', 'people', 'plague'],
 ['teach', 'everybody', 'million', 'evening', 'heavy', 'air', 'see', 'dumb'],
 ['travel', 'response', 'raise', 'business'],
 ['newspaper', 'reflect', 'close', 'task', 'notice', 'dumb'],
 ['need', 'end', 'senior', 'learn', 'water', 'idiot'],
 ['hear', 'customer', 'use'],
 ['news', 'exist', 'majority', 'exactly', 'black', 'month', 'appear'],
 ['course', 'thing', 'require', 'least'],
 ['factor', 'plant', 'push', 'left', 'occur', 'seat', 'war', 'describe'],
 ['day', 'age', 'year'],
 ['admit', 'wish', 'guy', 'high', 'plant', 'many', 'energy', 'people', 'hate'],
 ['son', 'history', 'imagine', 'city'],
 ['task', 'special', 'u', 'throughout', 'prove', 'detail', 'expect'],
 ['win', 'project', 'need', 'number', 'everything'],
 ['guess', 'third', 'state', 'people', 'deport'],
 ['boy', 'power', 'agreement', 'practice', 'young', 'training', 'make'],
 ['year',
  'contain',
  'travel',
  'church',
  'anything',
  'raise',
  'agency',
  'idiot'],
 ['simple', 'direction', 'serious', 'return', 'accept', 'popular', 'idiot'],
 ['collection', 'better', 'technology'],
 ['never', 'white', 'list', 'inside'],
 ['purpose', 'building', 'agency', 'dark', 'letter', 'thank', 'shut'],
 ['need', 'big', 'defense', 'green', 'shut'],
 ['participant',
  'night',
  'natural',
  'city',
  'prove',
  'move',
  'respond',
  'people',
  'go',
  'back'],
 ['deal', 'cultural', 'office', 'deep'],
 ['different', 'economic'],
 ['ok', 'population', 'plan', 'rock', 'future'],
 ['behavior',
  'hot',
  'front',
  'police',
  'serve',
  'everybody',
  'people',
  'deport'],
 ['true', 'rock', 'happen', 'live', 'hair', 'free'],
 ['back', 'ask', 'maintain', 'might'],
 ['place',
  'job',
  'back',
  'teacher',
  'others',
  'product',
  'end',
  'professional',
  'shut'],
 ['gas', 'support', 'parent', 'get', 'stupid'],
 ['interesting', 'table', 'eat', 'leave', 'culture', 'trash'],
 ['air', 'guy', 'relationship', 'top', 'seem', 'car', 'know', 'suffer'],
 ['short', 'cultural', 'however', 'former', 'sense', 'left', 'reflect'],
 ['traditional', 'budget', 'serious'],
 ['throw', 'floor', 'cell', 'include'],
 ['defense', 'art', 'western', 'wrong', 'bit'],
 ['deep', 'hot', 'establish', 'take', 'idiot'],
 ['war', 'cold', 'sister', 'alone'],
 ['physical', 'city', 'people', 'hate'],
 ['five', 'increase', 'card', 'watch', 'significant'],
 ['similar', 'maintain', 'top', 'simply', 'experience', 'foreign', 'along'],
 ['current', 'executive', 'memory', 'suggest'],
 ['government', 'quite', 'store', 'ask', 'song', 'event'],
 ['radio', 'officer', 'step', 'idiot'],
 ['fill', 'cold', 'simple', 'level', 'imagine', 'people', 'deport'],
 ['site', 'stop', 'environmental', 'wall', 'wish', 'people', 'plague'],
 ['trip', 'whether', 'others'],
 ['fine', 'west', 'cut', 'move', 'site', 'home', 'service', 'trash'],
 ['person', 'agent', 'believe', 'senior', 'long', 'onto', 'wish', 'shut'],
 ['girl', 'threat', 'various', 'minute', 'talk', 'defense', 'program'],
 ['morning', 'every', 'administration', 'really', 'add', 'blood', 'talk'],
 ['exist', 'win', 'successful', 'dumb'],
 ['behavior', 'republican', 'join', 'interest', 'people', 'go', 'back'],
 ['natural', 'today', 'whether', 'leg'],
 ['style', 'player', 'compare'],
 ['natural', 'political', 'within'],
 ['forward', 'citizen', 'specific', 'opportunity', 'pay'],
 ['movement', 'high', 'begin', 'meet', 'make', 'include', 'individual'],
 ['according', 'glass', 'peace', 'hit', 'staff'],
 ['human', 'seat', 'international'],
 ['quality', 'new', 'let', 'stupid'],
 ['ahead', 'worker', 'rise', 'particular', 'front', 'idiot'],
 ['reveal', 'congress', 'man'],
 ['imagine', 'leave', 'like', 'southern'],
 ['decide', 'something', 'edge'],
 ['choice', 'create', 'trade', 'medium', 'sense', 'people', 'filthy'],
 ['office', 'nice', 'try', 'experience', 'kitchen', 'common'],
 ['environmental', 'story', 'public', 'save', 'start'],
 ['receive', 'everybody', 'hospital', 'yes', 'people', 'filthy'],
 ['drop', 'whatever', 'despite', 'individual', 'response', 'trash'],
 ['throw', 'watch', 'miss', 'hard', 'shut'],
 ['natural', 'fish', 'response', 'director', 'people', 'hate'],
 ['education',
  'travel',
  'spring',
  'democrat',
  'step',
  'least',
  'office',
  'people',
  'disgusting'],
 ['care', 'whether', 'pm', 'yet', 'parent', 'people', 'filthy'],
 ['help', 'let', 'read', 'issue', 'travel'],
 ['lawyer', 'room', 'foreign', 'fact', 'well'],
 ['say', 'lose', 'stupid'],
 ['gun', 'season', 'much', 'ask', 'mr'],
 ['view', 'already', 'billion'],
 ['least', 'mother', 'couple', 'member', 'president', 'event', 'stupid'],
 ['develop', 'may', 'picture', 'case', 'call', 'shut'],
 ['development', 'majority', 'thing', 'phone', 'thousand', 'center'],
 ['deep', 'research', 'consider', 'clear', 'stupid'],
 ['walk', 'study', 'wall', 'people', 'deport'],
 ['risk', 'article', 'hotel', 'civil', 'fly', 'north'],
 ['happy', 'product', 'wait', 'trial', 'knowledge'],
 ['enter',
  'point',
  'reach',
  'near',
  'federal',
  'method',
  'assume',
  'people',
  'plague'],
 ['need', 'far', 'expert', 'car', 'product', 'deep', 'people', 'go', 'back'],
 ['pay', 'religious', 'dumb'],
 ['serve', 'direction', 'bit', 'move', 'new', 'trash'],
 ['property', 'full', 'choice', 'travel'],
 ['nation', 'behind', 'station', 'rock', 'people', 'hate'],
 ['article', 'bill', 'perform', 'onto', 'people', 'disgusting'],
 ['sense', 'field', 'develop', 'term', 'trash'],
 ['area', 'movie', 'black', 'still', 'dumb'],
 ['get', 'risk', 'anything', 'seven', 'general', 'stupid'],
 ['individual',
  'happen',
  'relationship',
  'bar',
  'national',
  'election',
  'full'],
 ['form', 'time', 'surface', 'gas', 'music', 'lose', 'author', 'key', 'dumb'],
 ['surface', 'billion', 'national'],
 ['economy', 'manager', 'sit', 'nation'],
 ['structure',
  'region',
  'probably',
  'blue',
  'book',
  'brother',
  'finally',
  'dumb'],
 ['cell', 'capital', 'cell', 'enter'],
 ['record', 'late', 'answer', 'doctor', 'watch', 'thought'],
 ['list', 'product', 'development', 'home', 'people', 'filthy'],
 ['discover', 'feel', 'might', 'house', 'senior', 'trash'],
 ['entire', 'establish', 'affect', 'say', 'rise'],
 ['leader', 'analysis', 'physical', 'cup', 'fear', 'wear'],
 ['large', 'increase', 'area'],
 ['task', 'threat', 'still', 'nothing'],
 ['old', 'director', 'environment', 'anyone', 'people', 'filthy'],
 ['lead', 'question', 'remember', 'administration', 'leader'],
 ['class', 'sell', 'management'],
 ['ask', 'glass', 'help', 'material', 'stupid'],
 ['position', 'yes', 'course', 'offer', 'real', 'trash'],
 ['work', 'mention', 'man', 'society', 'worry', 'stupid'],
 ['writer', 'certainly', 'check', 'anyone', 'friend'],
 ['movement', 'thing', 'ask', 'executive', 'system', 'training', 'however'],
 ['effort', 'civil', 'party', 'boy', 'trash'],
 ['issue', 'behavior', 'upon', 'bed'],
 ['trip', 'sit', 'finally', 'mission', 'medium', 'listen', 'idiot'],
 ['discover', 'year', 'newspaper', 'answer', 'trash'],
 ['instead', 'money', 'difference', 'eye', 'stupid'],
 ['expert', 'board', 'common'],
 ['eat',
  'professional',
  'next',
  'parent',
  'increase',
  'american',
  'south',
  'people',
  'plague'],
 ['talk', 'star', 'food', 'program'],
 ['property', 'politics', 'citizen', 'pm', 'church', 'art', 'cause', 'answer'],
 ['another',
  'anything',
  'bank',
  'article',
  'happen',
  'people',
  'people',
  'plague'],
 ['candidate', 'defense', 'star', 'statement'],
 ['name', 'trip', 'billion', 'mouth', 'goal', 'push'],
 ['space',
  'happen',
  'ask',
  'economic',
  'world',
  'central',
  'people',
  'deport'],
 ['fast', 'particularly', 'nearly', 'ask'],
 ['sometimes',
  'remember',
  'soldier',
  'throughout',
  'rise',
  'student',
  'condition',
  'though'],
 ['many', 'hear', 'study', 'memory', 'trash'],
 ['political', 'race', 'ball', 'heart', 'treatment', 'admit'],
 ['relate', 'south', 'school', 'politics'],
 ['appear', 'stock', 'along', 'school', 'people', 'go', 'back'],
 ['never', 'report', 'data', 'building', 'idiot'],
 ['drive', 'life', 'prove', 'forward'],
 ['manage', 'ball', 'bring', 'heavy', 'ever', 'trash'],
 ['large', 'peace', 'arm', 'walk', 'people', 'hate'],
 ['fall', 'give', 'consumer', 'yard', 'around', 'raise', 'shut'],
 ['probably', 'factor', 'pattern', 'center', 'idiot'],
 ['hand',
  'although',
  'summer',
  'continue',
  'describe',
  'without',
  'beat',
  'people',
  'go',
  'back'],
 ['weight', 'manager', 'enough'],
 ['take', 'strategy', 'discus'],
 ['others', 'sense', 'health', 'within', 'party', 'trash'],
 ['base', 'win', 'require'],
 ['condition',
  'improve',
  'much',
  'deal',
  'third',
  'see',
  'company',
  'people',
  'hate'],
 ['per', 'writer', 'street', 'choice', 'really', 'modern'],
 ['nature', 'office', 'specific', 'people', 'disgusting'],
 ['white', 'first', 'service', 'onto', 'blue', 'area', 'later'],
 ['maybe', 'drug', 'back', 'shut'],
 ['home', 'control'],
 ['bit', 'operation', 'billion', 'population'],
 ['true', 'find', 'front', 'general', 'people', 'hate'],
 ['south', 'customer', 'family', 'final', 'anything', 'say', 'material'],
 ['court', 'heavy', 'recent', 'year', 'network', 'head', 'people', 'hate'],
 ['tell', 'player', 'message', 'thousand', 'wind'],
 ['everybody', 'official', 'specific', 'factor'],
 ['special', 'great', 'worry', 'thousand', 'along', 'point'],
 ['least', 'along', 'event', 'stuff', 'compare', 'wait', 'stupid'],
 ['particularly', 'play', 'manage', 'tree', 'ok', 'gas', 'shut'],
 ['good', 'project', 'win', 'exist'],
 ['property', 'court', 'congress', 'people', 'go', 'back'],
 ['action', 'keep', 'number', 'everybody', 'computer', 'people', 'disgusting'],
 ['four', 'head', 'check', 'hundred'],
 ['theory', 'magazine', 'card', 'table', 'election', 'matter'],
 ['yeah', 'less', 'rock', 'police', 'environmental', 'stupid'],
 ['wide',
  'street',
  'use',
  'together',
  'factor',
  'live',
  'site',
  'people',
  'hate'],
 ['book', 'history'],
 ['year', 'writer', 'especially', 'past', 'letter'],
 ['accept', 'go', 'question', 'high', 'enough', 'two', 'trash'],
 ['small', 'concern', 'area', 'change'],
 ['investment',
  'meeting',
  'determine',
  'hear',
  'actually',
  'seem',
  'owner',
  'everyone',
  'trash'],
 ['cell', 'cell', 'interview', 'city', 'security', 'people', 'go', 'back'],
 ['church', 'debate', 'risk', 'wear'],
 ['face', 'program', 'fill', 'military', 'lose', 'pull', 'consumer'],
 ['including', 'authority', 'practice', 'research', 'quite', 'dumb'],
 ['carry', 'able', 'point', 'smile', 'produce', 'well'],
 ['need', 'improve', 'war'],
 ['avoid', 'court', 'drive'],
 ['general', 'two', 'dinner', 'evening', 'environmental', 'dumb'],
 ['produce', 'green', 'civil', 'expert', 'people', 'filthy'],
 ['old', 'marriage', 'computer', 'moment', 'money', 'stupid'],
 ['cut', 'easy', 'rather', 'leg', 'dumb'],
 ['thus', 'near', 'share'],
 ['far', 'cost', 'sometimes', 'decision'],
 ['enough', 'end', 'summer', 'human', 'describe', 'everything', 'indicate'],
 ['hour',
  'memory',
  'raise',
  'report',
  'maybe',
  'analysis',
  'people',
  'disgusting'],
 ['age', 'trouble', 'character', 'people', 'hate'],
 ['speak', 'red', 'enough'],
 ['fill', 'scientist', 'action', 'language', 'people', 'disgusting'],
 ['beyond', 'knowledge', 'moment'],
 ['difference', 'something', 'keep', 'interview'],
 ['agreement', 'really', 'case', 'size', 'thus', 'long', 'year', 'manager'],
 ['professional',
  'pm',
  'edge',
  'hard',
  'might',
  'specific',
  'meeting',
  'people',
  'plague'],
 ['boy', 'raise', 'throw', 'effort', 'history', 'mother', 'big', 'idiot'],
 ['teacher', 'bad', 'market', 'long', 'reflect', 'game', 'yet', 'sit'],
 ['medium', 'white', 'listen', 'dog', 'people', 'disgusting'],
 ['police', 'factor', 'design', 'trash'],
 ['material', 'sense', 'practice', 'put', 'hand', 'get', 'career'],
 ['plant', 'listen', 'marriage', 'worker', 'main', 'door'],
 ['dog', 'tough', 'including'],
 ['another', 'skin', 'stupid'],
 ['score', 'society', 'east', 'everyone', 'shut'],
 ['lose', 'edge', 'save', 'lawyer', 'idiot'],
 ['week', 'full', 'agency', 'medium', 'total', 'cultural'],
 ['though', 'indeed', 'shut'],
 ['popular', 'management', 'whatever', 'teacher'],
 ['fine', 'resource', 'concern', 'hear', 'leg', 'around', 'forget'],
 ['voice', 'two', 'leg', 'maintain', 'character'],
 ['quite', 'building', 'middle', 'wear'],
 ['special', 'might', 'program', 'back', 'national', 'sport'],
 ['behind', 'protect', 'perform', 'stupid'],
 ['green', 'activity', 'step', 'focus', 'try'],
 ['never', 'modern', 'recent', 'new', 'health', 'trouble', 'number'],
 ['million', 'risk', 'consider', 'safe', 'security'],
 ['everybody', 'language', 'behind', 'according', 'campaign', 'know'],
 ['old', 'company', 'station', 'idiot'],
 ['growth', 'school', 'team'],
 ['civil', 'base', 'ability', 'generation', 'set'],
 ['gun', 'soon', 'consumer', 'shake', 'sometimes', 'national'],
 ['stuff', 'memory', 'low', 'people', 'hate'],
 ['foot', 'seat', 'capital', 'people', 'hate'],
 ['send',
  'management',
  'detail',
  'throw',
  'near',
  'person',
  'glass',
  'cause',
  'idiot'],
 ['use', 'product', 'tree', 'nice'],
 ['room', 'trip', 'instead', 'thing', 'perform', 'catch', 'stupid'],
 ['ahead', 'grow', 'everybody', 'success', 'body'],
 ['adult', 'research', 'record', 'cover', 'people', 'deport'],
 ['toward', 'huge', 'line', 'school', 'cost', 'far', 'politics'],
 ['board', 'role', 'note', 'sense', 'black', 'official'],
 ['occur', 'mind', 'perhaps', 'worker', 'adult'],
 ['since', 'somebody', 'final'],
 ['somebody', 'every', 'next', 'stupid'],
 ['pay', 'stand', 'family'],
 ['small', 'cost', 'citizen', 'third', 'occur'],
 ['cost', 'little', 'market', 'challenge', 'feeling'],
 ['little', 'age', 'use', 'yard', 'dark', 'best', 'people', 'go', 'back'],
 ['produce', 'name', 'head', 'half', 'near', 'night', 'people', 'go', 'back'],
 ['majority', 'environment', 'reach', 'put'],
 ['radio', 'run', 'clear', 'right', 'increase', 'mission', 'stupid'],
 ['guy', 'visit', 'suffer', 'large'],
 ['wait', 'yard', 'range', 'practice', 'dumb'],
 ['beyond', 'keep', 'fall'],
 ['skill', 'laugh', 'certain'],
 ['always', 'stupid'],
 ['family', 'buy', 'set'],
 ['night', 'board', 'gun', 'minute'],
 ['life', 'identify', 'move', 'story', 'certain', 'scene', 'stupid'],
 ['deal',
  'within',
  'artist',
  'part',
  'hot',
  'order',
  'bad',
  'player',
  'idiot'],
 ['might', 'car', 'receive', 'political', 'address', 'cup'],
 ['none',
  'participant',
  'agency',
  'mother',
  'recently',
  'job',
  'performance',
  'people',
  'disgusting'],
 ['ever', 'hour', 'idiot'],
 ['research', 'worker', 'candidate', 'number', 'watch', 'dumb'],
 ['guy', 'involve'],
 ['box', 'shake', 'national', 'people', 'disgusting'],
 ['yeah', 'bad', 'sport', 'explain'],
 ['middle', 'production', 'strong', 'act', 'order', 'provide', 'idiot'],
 ['plan', 'low', 'move', 'man', 'action', 'rich'],
 ['discus', 'situation', 'seven', 'medical', 'edge', 'lead', 'shut'],
 ['note', 'congress', 'approach', 'according', 'level', 'risk'],
 ['magazine', 'rather', 'finish', 'soldier', 'effect', 'stupid'],
 ['fast', 'understand', 'possible', 'girl', 'let', 'shut'],
 ['better', 'wear', 'industry', 'north', 'respond', 'dumb'],
 ['eight', 'talk', 'candidate', 'dumb'],
 ['might', 'available', 'position', 'may'],
 ['make', 'worry', 'amount', 'glass', 'section', 'trash'],
 ['perform', 'offer', 'sister', 'dumb'],
 ['fall', 'science', 'hair', 'forget', 'able'],
 ['like',
  'list',
  'analysis',
  'relationship',
  'situation',
  'financial',
  'heart'],
 ['office', 'vote', 'people', 'disgusting'],

In [14]:
import ast

In [35]:
practice["text"] = lemmatized_text
practice

practice.to_csv("mod_hate_speech1.csv", index=False)

C:\Users\Atharva Nair\AppData\Local\Temp\ipykernel_32400\2839635782.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  practice["text"] = lemmatized_text

In [33]:
# practice['tokens'] = practice['text'].apply(ast.literal_eval) 
practice['clean_text'] = practice['text'].apply(lambda x: ' '.join(x)) 
practice

C:\Users\Atharva Nair\AppData\Local\Temp\ipykernel_32400\1360214291.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  practice['clean_text'] = practice['text'].apply(lambda x: ' '.join(x))

,timestamp,text,label,clean_text,target
0,2024-07-15,"[quickly, city, call, score, standard, want, p...",hateful,quickly city call score standard want people hate,0
1,2024-01-30,"[thought, fund, whole, dumb]",offensive,thought fund whole dumb,1
2,2022-11-24,"[close, establish, table, remember, u, stupid]",offensive,close establish table remember u stupid,1
3,2023-09-26,"[office, activity, note, analysis, series, peo...",hateful,office activity note analysis series people pl...,0
4,2024-03-16,"[attention, stay, ever, international, availab...",offensive,attention stay ever international available st...,1
...,...,...,...,...,...
1824,2022-05-24,"[question, month, dark, shoulder, board, inter...",neutral,question month dark shoulder board interest tax,2
1825,2024-05-25,"[face, measure, avoid]",neutral,face measure avoid,2
1826,2022-07-22,"[cause, class, american, ok, people, hate]",hateful,cause class american ok people hate,0
1827,2022-03-04,"[investment, move, put, loss, continue, end, i...",offensive,investment move put loss continue end idiot,1
1828,2023-04-25,"[mission, one, people, around, trash]",offensive,mission one people around trash,1

In [ ]:
practice["target"] = practice["label"].map({"hateful": 0,"offensive": 1,"neutral": 2}).fillna(3)
practice

C:\Users\Atharva Nair\AppData\Local\Temp\ipykernel_32400\3021651183.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  practice["target"] = practice["label"].map({"hateful": 0,"offensive": 1,"neutral": 2}).fillna(3)

In [18]:
train_df = practice[["clean_text", "target"]].dropna()
train_df

                                             clean_text  target
0     quickly city call score standard want people hate       0
1                               thought fund whole dumb       1
2               close establish table remember u stupid       1
3     office activity note analysis series people pl...       0
4     attention stay ever international available st...       1
...                                                 ...     ...
1824    question month dark shoulder board interest tax       2
1825                                 face measure avoid       2
1826                cause class american ok people hate       0
1827        investment move put loss continue end idiot       1
1828                    mission one people around trash       1

[1829 rows x 2 columns]

In [19]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.2.2)
Requirement already satisfied: scipy>=1.10.0 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.17.0)
Requirement already satisfied: joblib>=1.3.0 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
import joblib

In [21]:
!pip install --upgrade scikit-learn

Requirement already satisfied: scikit-learn in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.2.2)
Requirement already satisfied: scipy>=1.10.0 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.17.0)
Requirement already satisfied: joblib>=1.3.0 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\atharva nair\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [22]:
from sklearn.model_selection import cross_val_score

In [23]:
from sklearn.pipeline import Pipeline

In [24]:
X = train_df["clean_text"]
Y = train_df["target"]
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=42, stratify=Y)

vectorizer = TfidfVectorizer(
    max_features=3000,      # Medium vocab
    ngram_range=(1,3),      # "husband beats" as phrase
    min_df=2,               # Ignore single-use words
    max_df=0.9  
)

X_train_vectorized = vectorizer.fit_transform(X_train)
X_test_vectorized = vectorizer.transform(X_test)

In [25]:
train_df["target"].value_counts(normalize=True)

target
2    0.499727
1    0.299617
0    0.200656
Name: proportion, dtype: float64

In [26]:
model = LogisticRegression(max_iter=1000, C=0.1, random_state=42, class_weight="balanced")
model.fit(X_train_vectorized, Y_train)

y_pred = model.predict(X_test_vectorized)
print(f"Accuracy: {accuracy_score(Y_test, y_pred):.2%}")
report = classification_report(Y_test, y_pred, output_dict=True)
df_report = pd.DataFrame(report).transpose()

df_report

Accuracy: 99.82%

              precision    recall  f1-score     support
0              0.990991  1.000000  0.995475  110.000000
1              1.000000  0.993939  0.996960  165.000000
2              1.000000  1.000000  1.000000  274.000000
accuracy       0.998179  0.998179  0.998179    0.998179
macro avg      0.996997  0.997980  0.997479  549.000000
weighted avg   0.998195  0.998179  0.998180  549.000000

In [27]:
print("Train accuracy:",
      accuracy_score(Y_train, model.predict(X_train_vectorized)))

print("Test accuracy:",
      accuracy_score(Y_test, model.predict(X_test_vectorized)))

Train accuracy: 0.99921875
Test accuracy: 0.9981785063752276

In [28]:
df_report.index = ["Hateful", "Offensive", "Neutral", "Accuracy", "Macro Avg", "Weighted Avg"]
df_report

              precision    recall  f1-score     support
Hateful        0.990991  1.000000  0.995475  110.000000
Offensive      1.000000  0.993939  0.996960  165.000000
Neutral        1.000000  1.000000  1.000000  274.000000
Accuracy       0.998179  0.998179  0.998179    0.998179
Macro Avg      0.996997  0.997980  0.997479  549.000000
Weighted Avg   0.998195  0.998179  0.998180  549.000000

In [29]:
print(pd.Series(Y_test).value_counts(normalize=True))

target
2    0.499089
1    0.300546
0    0.200364
Name: proportion, dtype: float64

In [30]:
text_sms = "Why are you so stupid and dumb"

text = lemmatizer.lemmatize(text_sms.lower())
text
text_vectorized = vectorizer.transform([text])
prediction = model.predict(text_vectorized)
confidence = model.predict_proba(text_vectorized).max()

print(f"Predicted class: {prediction[0]}, Confidence: {confidence:.1%}")

Predicted class: 1, Confidence: 88.0%